project:
  type: book
  output-dir: docs

book:
  title: "Soil description handbook for New Zealand"
  author:
    - id: obrl
      name:
        given: "Lauren"
        family: "O'Brien"
      email: "soilstandards@landcareresearch.co.nz"
      orcid: "0000-0002-7336-2171"
      attributes:
        corresponding: true
      roles:
        - editing: lead
        - writing: lead
    - id: kd
      name:
        given: "Kirstin"
        family: "Deuss"
      orcid: "0000-0002-6531-0830"
      degrees: "PhD"
      roles:
        - editing: supporting
        - writing: supporting
    - id: aeg
      name:
        given: "Andre"
        family: "Eger"
      orcid: "0000-0001-8442-6815"
      degrees: "PhD"
      roles:
        - editing: supporting
        - writing: supporting
    - id: mjdg
      name:
        given: "J. D. G."
        family: "Milne"
      roles:
        - writing: supporting
    - id: cb
      name:
        given: "B."
        family: "Clayden"
      roles:
        - writing: supporting
    - id: pgs
      name:
        given: "P. G."
        family: "Singleton"
      roles:
        - writing: supporting
    - id: adw
      name:
        given: "A. D."
        family: "Wilson"
      roles:
        - writing: supporting
    - id: sdwg
      name:
        literal: "Soil Description Working Group"
      roles:
        - writing: supporting
  date: "2024-01-23"
  language: en
  page-navigation: true
  publisher: "Bioeconomy Science Institute Maiangi Taiao"
  publisher-place: "Palmerston North, New Zealand"
  reader-mode: true
  search: true
  cover-image: data/SDH_cover_2026.png
  cover-image-alt: "An image of the cover of the SDH third edition, light blue in colour."
  sharing:
    - linkedin
  repo-url: https://github.com/manaakiwhenua/NZ_soildesc_2024
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Soil Setting"
      chapters:
        - ss_01_background.qmd
        - ss_02_location.qmd
        - ss_03_geomorphology.qmd
        - ss_04_parent_material.qmd
        - ss_05_climate.qmd
        - ss_06_biota.qmd
        - ss_07_landuse_mgmt.qmd
        - ss_08_soils.qmd

    - part: "Soil surface and profile"
      chapters:
        - pr_01_site.qmd
        - pr_02_surface.qmd
        - pr_03_horizons.qmd

    - part: "Soil horizons"
      chapters:
        - hr_01_architecture.qmd
        - hr_02_colour.qmd
        - hr_03_texture.qmd
        - hr_04_weathering_features.qmd
        - hr_05_consistence.qmd
        - hr_06_chemical_properties.qmd

    - part: "Soil interpretations"
      chapters:
        - in_01_horizon_names.qmd
        - in_02_profile_behaviour.qmd
        - in_03_nzsc_reqs.qmd
    - acknowledgements.qmd
    - references.qmd
  appendices:
    - ap_equipment.qmd
    - ap_field_recording.qmd
    - ap_sampling.qmd
    - ap_classification.qmd
    - ap_compat.qmd
    - ap_province.qmd

bibliography: soil_desc_refs_2024.bib
csl: bsi-citation-style-202609.csl

format:
  html:
    theme:
      - cosmo
      - custom.scss
    date-modified: last-modified
    callout-appearance: "simple"
    css: styles.css
    lightbox: true
    toc-depth: 3
    toc-expand: true
    mermaid:
      theme: neutral
## no longer actively using:
#  docx:
#    reference-doc: bsi-custom-reference-doc.docx
#    toc: true
#    toc-depth: 2
#    toc-title: "Contents"
#    number-sections: true
#    number-depth: 4
#    link-citations: true

# global knitr options
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    fig.align: 'center'
    echo: false
    fig.show: 'hold'
    results: 'hold'
    warning: false
    message: false
    error: false

## Current dependencies
## renv::dependencies() |>
##   dplyr::distinct(Package) |>
##   dplyr::arrange(Package)
#
#              dplyr
#            ggplot2
#             ggtern
#                 gt
#           gtExtras
#            munsell
#              purrr
#          rmarkdown
#      rnaturalearth
# rnaturalearthhires
#                 sf
#            stringr
#             tibble
#          tidyverse
#               tmap
