# Recording data in the field {#sec-ap-fieldrec}

Recording field data in a regularised format helps ensure that consistently high standards are kept. Well-structured and complete soil profile descriptions are key supports for subsequent analytical work, including mapping tasks and analysis of laboratory data.

## Data entry forms {#sec-ap-fieldrec-forms}

Using a data entry form reduces the chance of forgetting to record particular data points, vs freehand notes. The consistent layout also makes it easier to review data for completeness and correctness, and compare sites.

Data entry forms should be laid out so that the process of filling them out roughly follows the process of field soil description itself. Each section should contain enough room for the parameter being recorded. A high-detail hard-copy field sheet should still fit on a single A4 page, despite the large number of potential parameters.

Forms can be deployed on paper, but they are vulnerable to wind and rain. Note-taking software on touchscreen tablets (e.g. Microsoft OneNote) can offer a robust alternative.

## App-based data entry {#sec-ap-fieldrec-apps}

Using a purpose-built app for data entry can reduce the double handling inherent to recording hard-copy data, freeing up office time. Apps do come with design, deployment and maintenance overheads that need to be taken into account, as well as a significant learning curve for paper-adapted users. Graphical user interfaces, despite their huge potential, can at the time of writing be surprisingly restrictive about layout and input options, and generally will take up more virtual 'page space' than a hard-copy sheet.

At the time of writing there is no consumer-grade app dedicated to recording New Zealand soils field data, but the ESRI and QGIS spatial software ecosystems have field data entry frameworks that can be adapted for soils fieldwork.

## Taking and managing photographs {#sec-ap-fieldrec-pics}

Site photographs provide a valuable record of the profile itself and the nature of the landscape in which it occurs. Photographs taken should include at least the following:

-   1–4 landscape shots from different angles, placing the site in context. Stand well back and where possible, slightly uphill. Try to capture reliable landmarks in the background and remove any extraneous objects (e.g. field equipment) that might be distracting.
-   1 clear photo of the ground condition around the profile, including a clearly marked measuring tape or stick for scale.
-   1 clear photo of the extracted profile or exposure with a measuring tape for scale. Ideally take this photograph after tidying the profile but before describing, so it can be viewed in a minimally disturbed state.
-   3–4 close-up photos of the profile, capturing 30–40 cm depth ranges. These should slightly overlap.

Consider the use of a small whiteboard to include the site identifier and date in at least the profile photo. Any further photos of e.g. concretions or other pedologically important soil features are optional.

Profile photographs should be taken in clear sunlight with the light behind the photographer, or in full shade. Avoid dappled or dim light, or angled shadows. Note that high-visibility clothing can sometimes reflect light onto profiles in a way that distorts colour.

Using a dedicated field data recording app to take photographs can ensure that they are always associated with the correct site identifier. Otherwise, photographs should be organised on a per profile basis as soon as possible after fieldwork. The quickest method is simply to place them in a folder named after the site identifier. Renaming image files and/or adding subject-matter tags can be useful for longer-term storage, but the process can be time-consuming.

### Photographic equipment {#sec-ap-fieldrec-picsgear}

Most users will default to their smartphone camera. This is usually safe, but some newer models default to enhancing photos in ways that are optimised for recreational use rather than scientific data recording. Users should make an effort to understand how their devices are processing photographs and disable any features that may alter the images too heavily.

## Minimum data requirements {#sec-mds}

Data recording requirements for classifying the profile against the *New Zealand Soil Classification* are available in @sec-nzsc123, and data needed for some other systems are in @sec-xcompat. Below in @tbl-mds, the minimum rapid, routine and detailed recording options described throughout the main text are summarised. Note that there is no reason not to record particular parameters in more detail than the minimum if they are of interest.

Rapid sites are for primarily for confirmation of soil type in a landscape that is already well-understood, or to support research work that is not primarily focused on soil processes. Rapid sites are also appropriate for students learning soil description for the first time. Routine sites are preferred for most soil description work, particularly in the exploratory phases of mapping. Detailed sites are preferred for soil-process-focused research work and for establishment of 'reference sites' representative of common soil profiles in a region.

+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Parameter                         | Rapid                                                                    | Routine                                                                                       | Detailed                                                                                                                                                                                            |
+:==================================+:=========================================================================+:==============================================================================================+:====================================================================================================================================================================================================+
| **Site - reference**              |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Site identifier                   | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Author                            | Main author                                                              | Main author and person in charge of sampling, if those differ                                 | List all participants and their roles                                                                                                                                                               |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Location                          | easting and northing to ±3 m                                             | easting, northing and elevation to ±3 m, equipment used, access notes where needed            | easting, northing, elevation and relative elevation above nearest stream to ±1 m, equipment used, access notes where needed                                                                         |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date                              | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Purpose                           | 🟨                                                                       | 🟨                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Selection method                  | 🟨                                                                       | 🟨                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exposure type                     | ✅                                                                       | ✅ (may not be [A]{.ceg} or [C2]{.ceg})                                                       | ✅ (must be [P1]{.ceg})                                                                                                                                                                             |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observation depth                 | ⛔                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Stopping early                    | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Setting - geomorphology**       |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Province                          | 🟨                                                                       | 🟨                                                                                            | 🟨                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landscape name                    | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landscape relief                  | ⛔                                                                       | 🟨 (median may be estimated)                                                                  | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landscape slope                   | ⛔                                                                       | 🟨 (median may be estimated)                                                                  | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landscape drainage                | ⛔                                                                       | ⛔                                                                                            | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landscape structural control      | 🟨                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landscape composition             | ⛔                                                                       | ⛔                                                                                            | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landform name                     | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landform slope                    | ⛔                                                                       | 🟨 (median may be estimated)                                                                  | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landform orientation              | ⛔                                                                       | 🟨                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Landform element                  | Morphology type                                                          | Morphology type                                                                               | Morphology type and relationship to neighbours                                                                                                                                                      |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slope length                      | ⛔                                                                       | ⛔                                                                                            | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exposure - regional               | ⛔                                                                       | ⛔                                                                                            | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exposure - local                  | ⛔                                                                       | 🟨 (if relevant)                                                                              | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Setting - parent material**     |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Geology - map code                | ⛔                                                                       | 🟨 (if relevant)                                                                              | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lithology                         | Dominant on landform (use lithology composition code if in doubt)        | Dominant on landform                                                                          | All observed on landform                                                                                                                                                                            |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mineralogy                        | ⛔                                                                       | 🟨                                                                                            | ✅ sample the profile                                                                                                                                                                               |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Setting - climate and weather** |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Climate - global                  | ⛔                                                                       | ⛔                                                                                            | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Climate - regional                | ⛔                                                                       | 🟨 (estimate macroclimatic zone)                                                              | ✅ (determine macroclimatic zone from best available data)                                                                                                                                          |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Climate - local                   | ⛔                                                                       | 🟨 (best available data from spatial estimates or nearby stations)                            | ✅(best available data from spatial estimates or nearby stations)                                                                                                                                   |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weather - current conditions      | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weather - current temperature     | 🟨 (estimate ok)                                                         | ✅ (estimate ok)                                                                              | ✅ (measure)                                                                                                                                                                                        |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weather - soil temperature        | ⛔                                                                       | 🟨 (if potentially needed to classify)                                                        | ✅ (measure at 10, 50, and 100 cm)                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weather - recent rainfall         | ⛔                                                                       | ✅                                                                                            | ✅ (days since last fall and total mm in previous 24 hours)                                                                                                                                         |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Setting - biota**               |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Vegetation                        | LCDB class                                                               | LUC class                                                                                     | RECCE description                                                                                                                                                                                   |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Soil fauna                        | 🟨 (worm count only)                                                     | 🟨 (worm count only)                                                                          | 🟨 (if relevant)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ecosystem                         | ⛔                                                                       | 🟨                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Setting - land**                |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Land cover                        | LCDB code                                                                | LCDB code                                                                                     | LCDB code                                                                                                                                                                                           |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Land use                          | Main land use to at least level 2                                        | Main land use, ancillary uses optional                                                        | Main and ancillary land uses. Prior uses and time since change if known                                                                                                                             |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Land management                   | Free text if known                                                       | Free text if known                                                                            | Free text, pursue history                                                                                                                                                                           |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Site - surface**                |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slope                             | ✅                                                                       | ✅ (no estimates)                                                                             | ✅(no estimates)                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Aspect                            | ✅ (class ok e.g. SW)                                                    | ✅ (numeric)                                                                                  | ✅(numeric)                                                                                                                                                                                         |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cover                             | ✅(% bare ground at least)                                               | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Disturbances                      | 🟨(if present)                                                           | ✅(and estimate time since)                                                                   | ✅(include additional notes)                                                                                                                                                                        |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Surface water                     | 🟨(if present)                                                           | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Surface cracking                  | 🟨(if present)                                                           | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Microrelief - natural             | 🟨(if present)                                                           | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Microrelief - anthropogenic       | 🟨(if present)                                                           | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Erosion - detailed                | ⛔                                                                       | ✅ (type)                                                                                     | ✅(type, severity, activity)                                                                                                                                                                        |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Deposition - detailed             | ⛔                                                                       | ✅ (type)                                                                                     | ✅(type, severity, activity)                                                                                                                                                                        |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Site - horizons**               |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Boundary lower depth              | single measurement to midpoint of transition                             | single measurement to midpoint of transition                                                  | median and range                                                                                                                                                                                    |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Boundary shape                    | 🟨(if observable)                                                        | 🟨(if observable)                                                                             | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Boundary distinctness             | ✅ (class)                                                               | ✅ (median)                                                                                   | ✅(median and range)                                                                                                                                                                                |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Infill features                   | 🟨(if observable)                                                        | 🟨(if observable)                                                                             | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Moisture status                   | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Depth to free water               | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lithology                         | ⛔(recorded for site overall)                                            | -   Main per horizon, distinguishing lithology of coarse fragments if they differ.            | All identifiable lithologies, per horizon, separately for coarse and fine mineral materials. Optionally, record for finer gradations of particle size as needed. Sample for confirmation as needed. |
|                                   |                                                                          | -   Main subsolum/bedrock (if encountered)                                                    |                                                                                                                                                                                                     |
|                                   |                                                                          | -   Use lithology composition code if in doubt (sparingly)                                    |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weathering                        | 🟨(only if subsolum encountered)                                         | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Parent material origin            | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - architecture**        |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Structure                         | Origin, grade. If pedal, shape, modal size as coarse or fine             | Origin, grade. If pedal, shape, median size in mm.                                            | Origin, grade. If pedal, shape, median size and range in mm. Describe nesting peds if present                                                                                                       |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fragments                         | -   Rock abundance from texture code                                     | -   Abundance of rock, natural and artefacts (confirm 0% of each). See also horizon lithology | -   Rock fragment abundance, lithology, shape, roundedness, roughness and weathering by as many size classes as preferred                                                                           |
|                                   | -   Natural fragment type and abundance if present in large amounts      | -   Rock fragment roundedness and weathering if present                                       | -   Natural fragment abundance, type, and size                                                                                                                                                      |
|                                   | -   Artefact type and abundance if present in large amounts              | -   Natural fragment type and abundance if present                                            | -   Artefact type, abundance, size, origin, fixation, shape, and degradation                                                                                                                        |
|                                   |                                                                          | -   Artefact type and abundance if present                                                    |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Roots                             | ✅(presence/absence)                                                     | ✅(abundance count total, overall position)                                                   | ✅(abundance count and position by size class)                                                                                                                                                      |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Voids                             | ✅(total areal percentage)                                               | ✅(areal percentage by type)                                                                  | ✅ (areal percentage and connectivity by type                                                                                                                                                       |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pores                             | ✅(presence/absence)                                                     | ✅(presence/absence)                                                                          | ✅(counts for macro and micro)                                                                                                                                                                      |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - subsolum**            |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lithology                         | 🟨(main, if encountered)                                                 | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weathering (geogenic features)    | ✅                                                                       | ✅                                                                                            | ✅                                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bedding                           | ✅(presence/absence, steepness class)                                    | ✅(angle, median thickness)                                                                   | ✅(angle, thicknesses)                                                                                                                                                                              |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fractures                         | ✅(presence/absence, close or not)                                       | ✅(type, orientation, spacing)                                                                | ✅(type, orientation, spacing)                                                                                                                                                                      |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - colour**              |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Matrix colour                     | Moist matrix colour                                                      | Moist matrix colour                                                                           | Moist and dry matrix colour(s)                                                                                                                                                                      |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Patterns                          | Type, moist colour short code. If redox, abundance of low-chroma colours | Type, moist colour short code. If redox, abundance of low-chroma colours                      | Type, moist colour, abundance.                                                                                                                                                                      |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - texture**             |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Texture class                     | Texture group plus dominant rock fragment and/or organic code as needed  | Texture class, rock and/or organic modifiers as preferred                                     | Texture class, rock and/or organic modifiers as detailed as possible                                                                                                                                |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Particle size                     | ⛔                                                                       | Estimate clay and sand percentages                                                            | Estimate clay and sand percentages                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - secondary features**  |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Concentrations                    | Type, abundance                                                          | Form, type, abundance                                                                         | Form, type, abundance, size                                                                                                                                                                         |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Coatings                          | Major type, abundance                                                    | Type, abundance                                                                               | Type, abundance                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pans                              | 🟨(use horizon names, record only if diagnostic)                         | Type, continuity, structure                                                                   | Type, continuity, structure                                                                                                                                                                         |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Stress features                   | Type if present                                                          | Type, abundance                                                                               | Type, abundance                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cryofeatures                      | 🟨Free text notes                                                        | 🟨Free text notes                                                                             | Free text notes                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - consistence tests**   | As needed for classification                                             | -   Unconfined strength (moist)                                                               | All applicable to the kind of material as per @tbl-cn-ct                                                                                                                                            |
|                                   |                                                                          | -   Mode of failure                                                                           |                                                                                                                                                                                                     |
|                                   |                                                                          |                                                                                               |                                                                                                                                                                                                     |
|                                   |                                                                          | otherwise as needed for classification                                                        |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - field tests**         | As needed for classification                                             | -   pH~f~ (any method)                                                                        | 🟨(only if intending to compare field and laboratory measures - assumes sampling for laboratory analysis)                                                                                           |
|                                   |                                                                          | -   NaF~f~ (if allophanic material suspected)                                                 |                                                                                                                                                                                                     |
|                                   |                                                                          |                                                                                               |                                                                                                                                                                                                     |
|                                   |                                                                          | Otherwise as needed for classification                                                        |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - horizon notation**    | Primary designations, redox signifiers, pan-related suffixes             | Secondary designations plus any other signifiers as needed                                    | Secondary designations plus any other signifiers as needed                                                                                                                                          |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile - interpretations**     |                                                                          |                                                                                               |                                                                                                                                                                                                     |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Drainage                          | ✅                                                                       | ✅(include assessment of alteration)                                                          | ✅(include assessment of alteration)                                                                                                                                                                |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Permeability                      | ✅                                                                       | ✅                                                                                            | 🟨(if not directly measured)                                                                                                                                                                        |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Root barriers                     | ✅(most limiting only, if any present)                                   | ✅(all and depths)                                                                            | ✅(all and depths)                                                                                                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Minimum data standards for rapid, routine and detailed sites. ✅means required, 🟨 means optional (and may be recorded after the field visit), and ⛔ means not required. {#tbl-mds .hover .striped}
