# Cross-compatibility {#sec-xcompat}

This handbook can inform soil and land assessment work carried out under other systems in New Zealand.

## NZ Land Use Capability classification {#sec-xluc}

The Land Use Capability (LUC) handbook [@lynn2009] encourages the user to identify soils from existing information sources (provided their quality is adequate for the target scale) before direct description. Where direct description is necessary, a minimum viable dataset for classifying soils according to the *New Zealand Soil Classification* is suggested below.

- Per site:
  - reference data (@sec-ref).
- Per Horizon:
  - horizon depths (@sec-pr-depths) and moisture status (@sec-pr-sws)
  - fine earth structure (@sec-hr-stru, rapid options)
  - rock fragments (@sec-rockfrag, rapid options)
  - matrix and pattern colours (@sec-col-matrix, @sec-col-patt, rapid options)
  - soil texture code (@sec-tex-rec)
  - pans (@sec-pan, rapid options)
  - consistence tests (@sec-cons, as needed for the *New Zealand Soil Classification* – see @nte-consnzsc)
  - field tests (@sec-ft, as needed for the *New Zealand Soil Classification* – see @nte-chemnzsc)
  - redox intensity (@sec-in-hdrng)
- Interpretations
  - drainage (@sec-in-drng)

Optionally, NZSC Family and Sibling identification can be added (@sec-in-nzscfamsib).

'Farm-scale' LUC mapping effectively operates at the landform level (@sec-gmph-lfm). Descriptions of slope, rock type, erosion and deposition, surface cover, and vegetation following the LUC handbook protocols can be made at that scale.

## Visual soil assessment {#sec-xvsa}

The visual soil assessment (VSA, @shepherd2000; @shepherd2000a) is a rapid soil quality assessment method commonly used in New Zealand agronomy. Those parts of the assessment dealing directly with soil morphology can be completed with reference to parts of this guide (@tbl-vsa).

| System | Component | Section | Notes |
|:-----------------|:-----------------|:-----------------|:------------------|
| Cropping, low-slope grazing, hill country | Structure and consistence | @sec-hr-stru | 'Consistence' is used differently in this standard |
| Cropping, low-slope grazing, hill country | Soil porosity | @sec-void, @sec-pore |  |
| Cropping, low-slope grazing, hill country | Soil colour | @sec-col-matrix | Only colour changes relative to a reference point are considered in VSA so Munsell notation is not required. |
| Cropping, low-slope grazing, hill country | Soil mottles | @sec-col-patt |  |
| Cropping, low-slope grazing, hill country | Earthworm counts | @sec-fauna-mega |  |
| Cropping | Tillage pan | @sec-pan | Pan type [C]{.ceg} |
| Cropping | Clod development | @sec-hr-stru |  |
| Cropping, hill country | Soil erosion | @sec-pr-dist | @sec-pr-erosion for detailed assessment. |
| Cropping, low-slope grazing | Surface ponding | @sec-pr-surfw (presence at time of observation), @sec-weath-rrain (time since rain event) |  |
| Low slope grazing, hill country | Surface relief | @sec-pr-dist, @sec-pr-micror | Surface disturbance type [AN]{.ceg}, and/or microrelief driver [B]{.ceg} with form [D]{.ceg} or [U]{.ceg} depending on severity |
| Low slope grazing, hill country | Bare ground | @sec-pr-surfcov | Surface cover types [BE]{.ceg}, [BR]{.ceg}, [BO]{.ceg} |
| Hill country | Topsoil depth | @sec-pr-depths |  |
| Hill country (forestry) | Humus types | @sec-hzn-convp |  |

: Mapping the VSA to the soil description manual {#tbl-vsa .hover width="\[20, 20, 30, 30\]"}
