---
format:
  html:
    mermaid:
      theme: neutral
---
# Data model {#sec-erds}

::: {.content-hidden when-format='html'}
This appendix demonstrates one way in which the contents of this manual can be structured in a database. Security, user management, change tracking, reporting, and other helper functionalities are left out for clarity. Audiovisual records, physical samples, sensor data and analytical results are also not considered. The size and complexity of the diagrams means that they are best viewed online at @sec-erds.

:::

::: {.content-visible when-format='html'}

This appendix demonstrates one way in which the contents of this manual can be structured in a database. Security, user management, change tracking, reporting, and other helper functionalities are left out for clarity. Audiovisual records, physical samples, sensor data and analytical results are also not considered.

## Overview

This overview shows the high-level relationships between each part of the standard. End nodes with "..." continue to be described in greater detail in a sub-diagram.

### Site

```{mermaid}
%%| label: fig-erd-ov-sit
%%| fig-cap: "Overview - conceptual relationships (Site)"

erDiagram
  direction LR
  Site ||--|| "Reference data..." : "has"
  Site ||--|| Location : "is at"
      Location ||--|| "Absolute location..." : "has"
      Location ||--|| "Relative location..." : "has"
  Site ||--|| Setting : "has"
    Setting ||--|| "Geomorphology..." : "has"
    Setting ||--|| "Parent Material..." : "has"
    Setting ||--|| "Climate and Weather..." : "has"
    Setting ||--|| "Vegetation..." : "has"
    Setting ||--|| "Land classification..." : "has"
  Site ||--|| "Soil Profile" : "contains"
    "Soil Profile" ||--|| "Surface..." : "has"
    "Soil Profile" ||--|{ "Horizon..." : "has at least one"
    "Soil Profile" ||--|{ "Interpreted properties..." : "has"
 
```

Note that a site is conceptualised here as a visit at a single point in time. Repeated visits to the same physical location need to be modelled with additional structures not included here.

### Setting

```{mermaid}
%%| label: fig-erd-ov-set
%%| fig-cap: "Overview - conceptual relationships (Setting)"

erDiagram
  direction LR
    Setting ||--|| Geomorphology : "has"
      Geomorphology ||--|| Province : "has"
      Geomorphology ||--|| "Landscape..." : "has"
      Geomorphology ||--|| "Landform..." : "has"
    Setting ||--|| "Parent Material" : "has"
      "Parent Material" ||--o{ Geology : "may have"
         Geology ||--o{ "Map Code" : "may have"
           "Map Code" ||--|| "Source" : "has" 
      "Parent Material" ||--|{ "Lithology" : "has"
      "Parent Material" ||--|{ "Origin" : "has"
    Setting ||--|| "Climate and Weather" : "has"
      "Climate and Weather" ||--|| Climate : "has"
        Climate ||--o| "Global..." : "may have"
        Climate ||--o| "Regional..." : "may have"
        Climate ||--o| "Local..." : "may have"
      "Climate and Weather" ||--|| Weather : "has"
        Weather ||--o| "Current weather" : "may have"
        Weather ||--o| "Current temperature" : "may have"
        Weather ||--|| "Recent Rainfall" : "has"
    Setting ||--|| Vegetation : "has"
      Vegetation ||--o| "Detailed description" : "may have one"
      Vegetation ||--|| "Vegetation Class" : "has"
    Setting ||--|| "Land classification" : "has"
      "Land classification"  ||--|| "Land Cover" : "has"
      "Land classification"  ||--|| "Land Use" : "has"
      "Land classification"  ||--|| "Land Management" : "has"

```

### Soil Profile

```{mermaid}
%%| label: fig-erd-ov-prf
%%| fig-cap: "Overview - conceptual relationships (profile)"

erDiagram
  direction LR
 "Soil Profile" ||--|| Surface : "has"
    Surface ||--|| "Morphometry..." : "has"
    Surface ||--|| "Features..." : "has"
    Surface ||--|| "Disturbances..." : "has" 
 "Soil Profile" ||--|{ "Horizon" : "has at least one"
    Horizon ||--|| "Extent..." : "has"
    Horizon ||--|| "Moisture status" : "has"
    Horizon ||--|| "Parent Material..." : "has"
    Horizon ||--|| "Architecture..." : "has"
    Horizon ||--|| "Colours..." : "has" 
    Horizon ||--|| "Texture..." : "has"
    Horizon ||--o{ "Weathering features..." : "may have"
    Horizon ||--o{ "Consistence tests..." : "may have"
    Horizon ||--o{ "Field tests..." : "may have"
    Horizon ||--|| "Interpreted properties..." : "has"
  "Soil Profile" ||--|{ "Interpreted properties" : "has"
    "Interpreted properties" ||--|| "Drainage" : "has"
    "Interpreted properties" ||--|| "Permeability" : "has"
    "Interpreted properties" ||--o{ "Rooting barriers..." : "may have"
    "Interpreted properties" ||--|| "NZ Soil Classification..." : "has"
    "Interpreted properties" ||--o| "Depth to water" : "may have"


```

## Site

### Reference data

```{mermaid}
%%| label: fig-erd-sit-ref
%%| fig-cap: "Site - reference data"

erDiagram
  direction LR
  "Reference data" ||--|| Identifier : "has"
    Identifier ||--o| Alias : "may have"
  "Reference data" ||--|{ Author : "has"
    Author ||--|| Name : "has"
    Author ||--o| Role : "may have"
  "Reference data" ||--|| "Date of observation" : "has"
  "Reference data" ||--|| "Purpose" : "has"
  "Reference data" ||--|| "Selection method" : "has"
  "Reference data" ||--|| "Exposure type" : "has"
  "Reference data" ||--|| "Observation max. depth" : "has"
  "Reference data" ||--o| "Early stop reason" : "may have"

```

### Location 

```{mermaid}
%%| label: fig-erd-sit-loc
%%| fig-cap: "Site - location data"

erDiagram
  direction LR
  Location ||--|| "Absolute location" : "has"
    "Absolute location" ||--|| "XY Coordinates" : "has"
      "XY Coordinates" ||--|| "Coord. Ref. System" : "has"
      "XY Coordinates" ||--|| "Expected error" : "has"
      "XY Coordinates" ||--|| "Data source" : "has"
    "Absolute location" ||--|| "Elevation" : "has"
      "Elevation" ||--|| "Vert. Coord. Ref. System" : "has"
      "Elevation" ||--|| "Vert. Expected error" : "has"
      "Elevation" ||--|| "El. Data source" : "has"
  Location ||--|| "Relative location" : "has"
    "Relative location" ||--o| "Triangulation description" : "may have"
    "Relative location" ||--o| "Relative elevation" : "may have"
      "Relative elevation" ||--|| Value : "has"
      "Relative elevation" ||--|| "Reference point" : "has"
    "Relative location" ||--o| "Access description" : "may have"

```

## Setting

### Geomorphology

```{mermaid}
%%| label: fig-erd-set-gmf
%%| fig-cap: "Setting - Geomorphology"

erDiagram
  direction LR
      Geomorphology ||--|| Landscape : "has"
        Landscape ||--|| "Lsc. Name" : "has"
        Landscape ||--o| "Lsc. Relief" : "may have"
          "Lsc. Relief" ||--|| "LscR Value" : "has"
          "Lsc. Relief" ||--o| "LscR Range" : "may have"
        Landscape ||--o| "Lsc. Slope" : "may have"
          "Lsc. Slope" ||--|| "LscS Value" : "has"
          "Lsc. Slope" ||--o| "LscS Range" : "may have"
        Landscape ||--o| "Lsc. Drainage pattern" : "may have"
        Landscape ||--o{ "Lsc. Structural Controls" : "may have"
      Geomorphology ||--|| Landform : "has"
        Landform ||--|| "Lfm. Name" : "has"
        Landform ||--|| "Lfm. Slope" : "has"
          "Lfm. Slope" ||--|| "LfmS Value": "has"
          "Lfm. Slope" ||--o| "LfmS Range" : "may have"
        Landform ||--|| "Lfm. Orientation" : "has"
          "Lfm. Orientation" ||--|| "LfmO Value": "has" 
          "Lfm. Orientation" ||--|| "LfmO Range": "has" 
        Landform ||--|{ "Lfm. Element" : "has"
          "Lfm. Element" ||--|| "LfmE Morphology" : "has"
          "Lfm. Element" ||--o| "LfmE rel. inclination" : "may have"
          "Lfm. Element" ||--o| "LfmE rel. enclosure" : "may have"
        Landform ||--o| "Lfm. Slope Length" : "may have"
          "Lfm. Slope Length" ||--|| "LfmSl Value" : "has"
          "Lfm. Slope Length" ||--|| "LfmSl Method" : "has"
        Landform ||--o| MTI : "may have"
            MTI ||--o{ "MTI Bearing" : "has"
              "MTI Bearing" ||--|| "MTI Angle" : "has"
```

### Climate

```{mermaid}
%%| label: fig-erd-set-cli
%%| fig-cap: "Setting - Climate"

erDiagram
  direction LR
  Climate ||--o| Global : "may have"
    Global ||--|| "Gl. Classification" : "has"
      "Gl. Classification" ||--|| "Gl. Cl. Source" : "has"
  Climate ||--o| Regional : "may have"
    Regional ||--|| "Rg. Classification" : "has"
      "Rg. Classification" ||--|| "Rg. Cl. Source" : "has"
  Climate ||--|| Local : "has"
    Local ||--|| "Lc. Classification" : "has"
      "Lc. Classification" ||--|| "Lc. Cl. Source" : "has"
    Local ||--o| Rainfall : "may have"
      Rainfall ||--o| "Rf Tot. Ann" : "may have"
        "Rf Tot. Ann" ||--|| "RFTA Source" : "has"
      Rainfall ||--o| "Rf. Seasonality" : "may have"
        "Rf. Seasonality" ||--|| "RFTS Source" : "has"
    Local ||--o| Temperature : "may have"
      Temperature ||--o| "Temp Mean Ann." : "may have"
        "Temp Mean Ann." ||--|| "TMA Source" : "has"
      Temperature ||--o| "Temp Mean Sum." : "may have"
        "Temp Mean Sum." ||--|| "TMS Source" : "has"
      
```

Note that other values mentioned in @sec-clim-rfall through to @sec-clim-wind may potentially be stored in a similar manner to that described above for local rainfall and temperature data, but it may be more efficient not to do so where the values are already published in continuous data surfaces.

## Profile

### Surface

```{mermaid}
%%| label: fig-erd-prf-sfc
%%| fig-cap: "Profile - soil surface"

erDiagram
  direction LR
  Surface ||--|| Morphometry : "has"
   Morphometry ||--|| Slope : "has"
     Slope ||--|| "Sl. Value" :  "has"
     Slope ||--o| "Sl. Range" :  "may have"
   Morphometry ||--|| Aspect: "has"
     Aspect ||--|| "A. Value" :  "has"
     Aspect ||--o| "A. Range" :  "may have"
   Morphometry ||--o| TSI : "may have"
     TSI ||--o{ "TSI Bearing" : "has"
       "TSI Bearing" ||--|| "TSI Angle" : "has"
  Surface ||--|| Features : "has"
    Features ||--|| Cover : "has"
      Cover ||--|{ "Cover Type" : has
        "Cover Type"||--|| "C. Abundance" : has 
    Features ||--o| Water : "may have"
      Water ||--|| "Water type" : "has"
      Water ||--o| "Wt. Persistence" : "may have"
    Features ||--o| Cracks : "may have"
      Cracks ||--|| Width : "has"
      Cracks ||--|| Depth : "has"
      Cracks ||--|| Spacing : "has"
      Cracks ||--o| "Ck. Persistence" :  "may have"
      Cracks ||--o| "Ck. Arrangement" :  "may have"
    Features ||--|| Microrelief : "has"
      Microrelief ||--|{ "Natural Microrelief" : "has"
        "Natural Microrelief" ||--|| "MR Type" : "has"
        "Natural Microrelief" ||--o| "MR Form" : "may have"
        "Natural Microrelief" ||--o| "MR Height" : "may have"
        "Natural Microrelief" ||--o| "MR Spacing" : "may have"
      Microrelief ||--o{ "Anthropogenic Microrelief" : "may have"
        "Anthropogenic Microrelief" ||--|| "AMR Type" : "has"
        "Anthropogenic Microrelief" ||--o| "AMR Height" : "may have"
        "Anthropogenic Microrelief" ||--o| "AMR Spacing" : "may have"
    Surface ||--||Disturbances : "has" 
      Disturbances ||--|{ "Recent Disturbances" : "has"
        "Recent Disturbances" ||--|| "Dist. Type" : "has"
        "Recent Disturbances" ||--o| "Dist. Recency Class" : "may have"
        "Recent Disturbances" ||--o| "Dist. Recency Days" : "may have"
      Disturbances ||--o{ Erosion : "may have"
        Erosion ||--|| "Er. Type" : "has"
        Erosion ||--|| Activity : "has"
        Erosion ||--|| "Er. Severity" : "has"
      Disturbances ||--o{ Deposition : "may have"
        Deposition ||--|| "Dp. Type" : "has"
        Deposition ||--|| Activity : "has"
        Deposition ||--|| "Dp. Severity" : "has"

```

### Horizons

```{mermaid}
%%| label: fig-erd-hzn
%%| fig-cap: "Profile - Soil horizons"

erDiagram
  direction LR
  Horizon ||--|| "Extent" : "has"
    Extent ||--|| "Depths..." : "has"
    Extent ||--|| "Boundary..." : "has"
  Horizon ||--o{ "Infill features" : "may have"
     "Infill features" ||--|| "IF Type" : has
     "Infill features" ||--o| "IF Material" : "may have"
  Horizon ||--|| "Moisture status" : "has"
  Horizon ||--|| "Parent Material" : "has"
    "Parent Material" ||--|{ "Lithology" : "has one or more"
    "Parent Material" ||--|{ "Mineralogy" : "has one or more"
    "Parent Material" ||--|| "Weathering status" : "has"
    "Parent Material" ||--|{ "Origin" : "has one or more"
  Horizon ||--|| Architecture : "has one"
    Architecture ||--|{ "Structure..." : "has one or more"
    Architecture ||--o{ "Fragments..." : "may have"
    Architecture ||--o{ "Roots..." : "may have"
    Architecture ||--o{ "Voids and pores..." : "may have"
    Architecture ||--o{ "Subsolum features..." : "may have"
  Horizon ||--|| Colours : "has" 
    Colours ||--|{ "Matrix colour..." : "has"
    Colours ||--o{ "Colour patterns..." : "has"
  Horizon ||--|| Texture : "has"
    Texture ||--|| "Texture group" : "has"
    Texture ||--|| "Texture class..." : "has"
    Texture ||--|| "PSD (estimate)..." : "has a"
  Horizon ||--o{ "Weathering features" : "may have"
    "Weathering features" ||--o{ "Concentrations..." : "may have"
    "Weathering features" ||--o{ "Coatings..." : "may have"
    "Weathering features" ||--o{ "Pan..." : "may be a"
    "Weathering features" ||--o{ "Stress Features..." : "may have"
  Horizon ||--o{ "Consistence tests" : "may have"
    "Consistence tests" ||--|| "C. Test parameter" : "has"
    "Consistence tests" ||--|| "C. Test method" : "has"
    "Consistence tests" ||--|| "C. Test result" : "has"
    "Consistence tests" ||--|| "C. Moisture Status" : "has"
  Horizon ||--o{ "Field tests" : "may have"
    "Field tests" ||--|| "F. Test parameter" : "has"
    "Field tests" ||--|| "F. Test method" : "has"
    "Field tests" ||--|| "F. Test Result" : "has"
  Horizon ||--|| "Interpreted properties" : "has"
    "Interpreted properties" ||--|| "Horizon Notation..." : "has"
    "Interpreted properties" ||--|| "Horizon drainage class" : "has"
    "Interpreted properties" ||--|| "Horizon permeability class" : "has"

```

Notes:

-  Consistence tests can be modelled separately from soil horizons, in which case each combination of test parameter, method, result and moisture status would be conceptualised as belonging to the soil profile, and be associated with a point or range depth measurement.
-  Field tests can be modelled separately from soil horizons, in which case each combination of test parameter, method, and result would be conceptualised as belonging to the soil profile, and be associated with a point or range depth measurement.


#### Extent

```{mermaid}
%%| label: fig-erd-hzn-ext
%%| fig-cap: "Horizons  - extent"

erDiagram
  direction LR
  Horizon ||--|| Extent : "has"
    Extent ||--|| Depths : "has"
      Depths ||--|| "Upper depth" : "has"
        "Upper depth" ||--|| "UD Value" : has
        "Upper depth" ||--o| "UD Range" : "may have"
      Depths ||--|| "Lower depth" : "has"
        "Lower depth" ||--|| "LD Value" : has
        "Lower depth" ||--o| "LD Range" : "may have"
    Extent ||--|| Boundary : "has"
      Boundary ||--o| "Bdy Shape" : "may have"
      Boundary ||--o| "Bdy Distinctness" : "may have"
        "Bdy Distinctness" ||--|| "BD Value" : "has"
        "Bdy Distinctness" ||--o| "BD Range" : "may have"

```

#### Architecture

```{mermaid}
%%| label: fig-erd-hzn-arc
%%| fig-cap: "Horizons - Architecture"

erDiagram
  direction LR
  Architecture ||--|{ Structure : "has one or more"
    Structure ||--|| "Str. Origin" : "has"
    Structure ||--|| "Str. Development" : "has"
    Structure ||--o| "Str. Shape" : "may have"
    Structure ||--o| "Str. Size" : "may have"
      "Str. Size" ||--|| "StrS Value" : has
      "Str. Size" ||--o| "StrS Range" : "may have"
  Architecture ||--o{ Fragments : "may have"
      Fragments ||--o{ "Rock Fragments..." : "may have"
      Fragments ||--o{ "Natural Fragments..." : "may have"
      Fragments ||--|{ "Artefacts..." : "may have"
  Architecture ||--o{ Roots : "may have"
    Roots ||--|| "Root Abundance" : "has"
    Roots ||--o{ "Root Size" : "may have"
      "Root Size" ||--|| "RS Abundance" : "may have"
    Roots ||--|| "Root Position" : "has"
  Architecture ||--o{ "Voids and pores" : "may have"
    "Voids and pores" ||--o{ "Voids..." : "may have"
    "Voids and pores" ||--o{ "Pores..." : "may have" 
  Architecture ||--o{ "Subsolum features" : "may have"
    "Subsolum features" ||--o| "SS Lithology" : "may have"
    "Subsolum features" ||--o| "SS Weathering" : "may have"
    "Subsolum features" ||--o| "SS Bedding" : "may have"
      "SS Bedding" ||--|| "SSB Angle" : "has"
      "SS Bedding" ||--|| "SSB Thickness" : "has"
    "Subsolum features" ||--o{ Fractures : "has"
      Fractures ||--|| "SSF Type" : "has"
        "SSF Type" ||--o| "SSFT Orientation" : "may have"
    
```

##### Fragments

```{mermaid}
%%| label: fig-erd-hzn-arc-frg
%%| fig-cap: "Horizons - Architecture - Fragments"

erDiagram
  direction LR
  Fragments ||--o{ "Rock Fragments" : "may have"
        "Rock Fragments" ||--|| "RF Abundance" : "has"
          "RF Abundance" ||--|| "RFA Value" : "has"
          "RF Abundance" ||--o| "RFA Range" : "may have"
        "Rock Fragments" ||--|{ "RF Lithology" : "has"
        "Rock Fragments" ||--o| "RF Shape" : "may have"
          "RF Shape" ||--o| "RF Form" : "may have"
          "RF Shape" ||--o| "RF Roundedness" : "may have"
          "RF Shape" ||--o| "RF Roughness" : "may have"
        "Rock Fragments" ||--o| Weathering : "may have"
        "Rock Fragments" ||--o{ "RF Size Class" : "may have"
          "RF Size Class" ||--|| "RFC Abundance" : "has"
            "RFC Abundance" ||--|| "RFCA Value" : "has"
            "RFC Abundance" ||--o| "RFCA Range" : "may have"
          "RF Size Class" ||--o{ "RFC Lithology" : "may have"
          "RF Size Class" ||--o| "RFC Shape" : "may have"
            "RFC Shape" ||--o| "RFC Form" : "may have"
            "RFC Shape" ||--o| "RFC Roundedness" : "may have"
            "RFC Shape" ||--o| "RFC Roughness" : "may have"
          "RF Size Class" ||--o| "RF Weathering" : "may have"
    Fragments ||--o{ "Natural Fragments" : "may have"
        "Natural Fragments" ||--|| "NF Abundance" : "has"
            "NF Abundance" ||--|| "NFA Value" : "has"
            "NF Abundance" ||--o| "NFA Range" : "may have" 
        "Natural Fragments" ||--o{ "NF Type" : "may have"
          "NF Type" ||--|| "NFT Abundance" : "has"
            "NFT Abundance" ||--|| "NFTA Value" : "has"
            "NFT Abundance" ||--o| "NFTA Range" : "may have"
          "NF Type" ||--|| "NFT Size" : "has"
            "NFT Size" ||--|| "NFTS Value" : "has"
            "NFT Size" ||--o| "NFTS Range" : "may have"  
    Fragments ||--|{ Artefacts : "may have"
        Artefacts ||--|| "AF Abundance" : "has"
          "AF Abundance" ||--|| "AFA Value" : "has"
          "AF Abundance" ||--o| "AFA Range" : "may have" 
        Artefacts ||--o{ "AF Type" : "may have"
          "AF Type" ||--|| "AFT Abundance" : "has"
            "AFT Abundance" ||--|| "AFTA Value" : "has"
            "AFT Abundance" ||--o| "AFTA Range" : "may have"
          "AF Type"  ||--o| "AFT Size" : "may have"
            "AFT Size" ||--|| "AFTS Value" : "has"
            "AFT Size" ||--o| "AFTS Range" : "may have"  
          "AF Type"  ||--o| "AFT Origin" : "may have"
          "AF Type"  ||--o| "AFT Fixation" : "may have"
          "AF Type"  ||--o| "AFT Shape" : "may have"
          "AF Type"  ||--o| "AFT Degradation" : "may have"
        
```

##### Voids and Pores


```{mermaid}
%%| label: fig-erd-hzn-arch-vp
%%| fig-cap: "Horizons - Architecture - Voids and Pores"

erDiagram
  direction LR
    "Voids and pores" ||--o{ Voids : "may have"
      Voids ||--|| "Void Abundance" : "has"
        "Void Abundance" ||--|| "VA Value" : "has"
        "Void Abundance" ||--o| "VA Range" : "may have"  
      Voids ||--o| "Void Connectivity" : "may have"
      Voids ||--o{ "Void Type" : "may have"
        "Void Type" ||--|| "VT Abundance" : "has"
          "VT Abundance" ||--|| "VTA Value" : "has"
          "VT Abundance" ||--o| "VTA Range" : "may have" 
        "Void Type" ||--o| "VT Connectivity" : "may have"
    "Voids and pores" ||--o{ Pores : "may have" 
      Pores ||--o| "Pore Presence" : "may have"
      Pores ||--o{ "Pore Size Class" : "may have"
        "Pore Size Class" ||--|| "Pore Abundance" : "may have"
          "Pore Abundance" ||--|| "PA Value" : "has"
          "Pore Abundance" ||--o| "PA Range" : "may have" 

```

#### Colours

```{mermaid}
%%| label: fig-erd-hzn-col
%%| fig-cap: "Horizons - Colour"

erDiagram
  direction LR
  Colours ||--|{ "Matrix colour" : "has"
    "Matrix colour" ||--|| Hue : "has"
    "Matrix colour" ||--|| Value : "has"
    "Matrix colour" ||--|| Chroma : "has"
    "Matrix colour" ||--|| "Moisture Status" : "has"
  Colours ||--o{ "Colour patterns" : "may have"
    "Colour patterns" ||--|| Type : "has"
    "Colour patterns" ||--o| "Shape" : "may have"
    "Colour patterns" ||--|| "CP Abundance" : "has"
      "CP Abundance" ||--|| "CPA Value" : "has"
      "CP Abundance" ||--o| "CPA Range" : "may have" 
    "Colour patterns" ||--o| "CP Size" : "may have"
      "CP Size" ||--|| "CPS Value" : "has"
      "CP Size" ||--o| "CPS Range" : "may have"    
    "Colour patterns" ||--o| Contrast : "may have"
    "Colour patterns" ||--|| "CP Colour" : "has"
      "CP Colour" ||--o| "CP Short Colour" : "may have"
      "CP Colour" ||--o| "CP Hue" : "may have"
      "CP Colour" ||--o| "CP Value" : "may have"
      "CP Colour" ||--o| "CP Chroma" : "may have"
      "CP Colour" ||--|| "CP Moisture Status" : "has"
    
```


#### Texture

```{mermaid}
%%| label: fig-erd-hzn-tex
%%| fig-cap: "Horizons - Texture class"

erDiagram
  direction LR
  Texture ||--|| "Texture Class" : "has"
    "Texture Class" ||--o| "Fine Earth Texture Code" : "may have"
      "Fine Earth Texture Code" ||--o| "FE Sand size mod" : "may have"  
      %% main , major or minor component:
      "Fine Earth Texture Code" ||--|| "FE position" : "has"   
    "Texture Class" ||--o| "Rock Fragment Code" : "may have"
      "Rock Fragment Code" ||--o| "RF size mod" : "may have"   
      "Rock Fragment Code" ||--|| "RF position" : "has"  
    "Texture Class" ||--o| "Organic Matter Code" : "may have"
      "Organic Matter Code" ||--o| "OM decomp. mod" : "may have"   
      "Organic Matter Code" ||--o| "OM origin mod" : "may have" 
      "Organic Matter Code" ||--|| "OM position" : "has"  
   Texture ||--|| "PSD (estimate)" : "may have"
     "PSD (estimate)" ||--|| "Clay content" : "has"
       "Clay content" ||--|| "Clay value" : "has"
       "Clay content" ||--o| "Clay range" : "may have"
     "PSD (estimate)" ||--|| "Sand content" : "has"
       "Sand content" ||--|| "Sand value" : "has"
       "Sand content" ||--o| "Sand range" : "may have"   
```

#### Weathering Features

```{mermaid}
%%| label: fig-erd-hzn-wft
%%| fig-cap: "Horizons - Weathering Features"

erDiagram
  direction LR
    "Weathering features" ||--o{ "Concentrations" : "may have"
      "Concentrations" ||--|| "CF Form" : "has"
      "Concentrations" ||--|| "CF Type" : "has"
      "Concentrations" ||--|| "CF Abundance" : "has"
        "CF Abundance" ||--|| "CFA Value" : "has"
        "CF Abundance" ||--o| "CFA Range" : "may have"
      "Concentrations" ||--|| "CF Size" : "has"
        "CF Size" ||--|| "CFS Value" : "has"
        "CF Size" ||--o| "CFS Range" : "may have"
    "Weathering features" ||--o{ "Coatings" : "may have"
      "Coatings" ||--|| "CT Type" : "has"
      "Coatings" ||--|| "CT Abundance" : "has"
        "CT Abundance" ||--|| "CTA Value" : "has"
        "CT Abundance" ||--o| "CTA Range" : "may have"
    "Weathering features" ||--o{ "Pan" : "may be a"
      "Pan" ||--|| "Pan Type" : "has"
      "Pan" ||--o| "Pan Continuity" : "may have"
      "Pan" ||--o| "Pan Structure" : "may have"
    "Weathering features" ||--o{ "Stress Features" : "may have"
      "Stress Features" ||--|| "SF Type" : has
      "Stress Features" ||--o| "SF Abundance" : has
        "SF Abundance" ||--|| "SFA Value" : "has"
        "SF Abundance" ||--o| "SFA Range" : "may have"

```

#### Interpreted Properties

##### Horizon notation

```{mermaid}
%%| label: fig-erd-hzn-not
%%| fig-cap: "Horizons - Interpreted Properties - Notation"

erDiagram
  direction LR
  "Horizon notation" ||--|| "Primary designation" : "has"
  "Horizon notation" ||--|| "Secondary designation" : "has"
  "Secondary designation" ||--o| "Redox suffix" : "has"
  "Secondary designation" ||--o{ "Other suffix" : "has"
  "Secondary designation" ||--|| "Subhorizon Index" : "has"
  "Secondary designation" ||--|| "Lithological prefix" : "has"
  "Secondary designation" ||--o| "Burial indicator" : "has"
  "Secondary designation" ||--o| "Anthropic indicator" : "has"
  

```

### Interpreted Properties

#### New Zealand Soil Classification

```{mermaid}
%%| label: fig-erd-prf-int-nzsc
%%| fig-cap: "Profile - Interpreted Properties - New Zealand Soil Classification"

erDiagram
  direction LR
  "NZSC" ||--|| "NZSC Order" : "has"
    "NZSC Order" ||--|| "NZSC Group" : "has"
      "NZSC Group" ||--|| "NZSC Subgroup" : "has"
        "NZSC Subgroup" ||--|| "NZSC Family" : "has"
          "NZSC Family" ||--|| "Soil profile material class" : "has"
          "NZSC Family" ||--|| "Rock Class (profile and/or bedrock stone)" : "has"
          "NZSC Family" ||--|| "Rock Class (fine earth)" : "has"
          "NZSC Family" ||--|| "Texture group class" : "has"
          "NZSC Family" ||--|| "Permeability class" : "has"
          "NZSC Family" ||--|| "Parent material origin class" : "has"
          "NZSC Family" ||--|| "NZSC Sibling" : "has"
            "NZSC Sibling" ||--|| "Depth Class" : "has" 
            "NZSC Sibling" ||--|| "Topsoil Stone Class" : "has" 
            "NZSC Sibling" ||--|| "Texture Class" : "has" 
            "NZSC Sibling" ||--|| "Drainage Class" : "has" 
            "NZSC Sibling" ||--|| "Misc. Class" : "has" 
            "NZSC Sibling" ||--|{ "Functional Horizon" : "has" 
            "Functional Horizon" ||--|| "Permeability" : "has"

```

#### Rooting barriers

```{mermaid}
%%| label: fig-erd-prf-int-rb
%%| fig-cap: "Profile - Interpreted Properties - Rooting barriers"

erDiagram
  direction LR
  "Rooting barrier" ||--o{ "Barrier type" : "may have"
    "Barrier type" ||--|| "Barrier depth" : "has"
      "Barrier depth" ||--|| "BD Value" : "has"
      "Barrier depth" ||--o| "BD Range" : "may have"

```

:::
