# Land provinces {#sec-ap-prov}

## North Island {#sec-ap-prov-nil}

### Northland hills and dunes - NN {#sec-ap-prov-nn .unnumbered}

Rolling low hills of sedimentary and mafic igneous rocks mixed together and emplaced by fault movement. These materials have eroded away in some areas, revealing the underlying basement rocks, and have otherwise been punctuated by volcanic activity, creating a patchy overlay of basaltic cones and lava fields. Large coastal sand dune systems have formed on the north-west coast along with smaller sand deposits on the east coast. Low mangrove- and salt-flats fringe many of the bays and river mouths. Many small islands occur off the east coast. The region's landscapes are older than most of the country and are unaffected by glaciation.

### Waikato to Bay of Plenty plains and volcanics - NL {#sec-ap-prov-nl .unnumbered}

Lowlands and hill country margins of the Waikato and Bay of Plenty form infilled basins and plains comprised of Late Pliocene and Quaternary volcanogenic alluvium and peats. The Kaimai and Coromandel Ranges to the east are predominately composed of Miocene and Pliocene volcanics of the Coromandel Volcanic Zone and basement greywacke (Waipapa composite terrane). Older andesitic volcanics of the Kiwitahi and Alexandra Volcanic Groups are distributed across the province and in some cases form large steep sided stratovolcanoes. Younger volcanic activity formed small cones and basalt sheets of the Auckland and South Auckland Volcanic Fields. Late Pliocene to Holocene central North Island tephras mantle slopes up to 35 degrees. Particularly on older stable land surfaces, composite tephras form deposits several metres thick.

### Waikato sedimentary hills - NW  {#sec-ap-prov-nw .unnumbered}

Strongly rolling, moderately steep to steep deeply dissected greywacke and Tertiary hill country of western Waikato (north of the Mokau River), Haupuakohe and Hunua Ranges and adjacent hill country in northern Waikato and south east Auckland. Composed of Waipapa and Murihiku terrane overlain by Tertiary sedimentary rocks predominantly of the Te Kuiti Group but overlain by Miocene rocks of the Waitemata Group in the north and Mahoenui and Mokau Groups in the south which forms the boundary with the Southern and eastern sedimentary hills province. Late Quaternary/Holocene central North Island tephras mantle slopes up to 35 degrees. Dune sands and beach deposits have formed a narrow, discontinuous strip along the west coast from Mokau to Port Waikato.

### Central Volcanic Zone - NV  {#sec-ap-prov-nv .unnumbered}

The geologically young landscape of the central volcanic zone is dominated by the effects of Late Quaternary volcanism and faulting associated with the Taupo Volcanic Zone (TVZ). TVZ rocks are dominated by ignimbrites erupted from large caldera forming volcanoes that have produced a series of ignimbrite plateaux and collapsed caldera basins and associated lakes. Older calderas have been largely infilled by more recent caldera eruptions. Small areas are occupied by rhyolitic lava domes and minor andesitic and basaltic volcanoes. Tephra eruptions especially over the last 20,000 years mantle the whole region making this province unique in that, apart from on the steepest most eroded slopes, soils are not developed from the underlying rock, but from proximal tephra deposits and fluvially reworked tephras.

### Stratovolcanoes and ringplains - NT {#sec-ap-prov-nt .unnumbered}

High, isolated Quaternary volcanic peaks of andesite-dominated pyroclastic materials surrounded by gently sloping, dissected, tephra-covered plains constructed from repeated cone collapse events. The cone surfaces comprise a mix of scree slopes and lava flows. The ringplains are dominated by deep, extensive volcanic ash cover, with some areas of hilly, rocky lahar mounds and some areas of shallow tephra over sandy to stony debris avalanche materials. Debris avalanche deposits may be loose or welded by heat and friction into ignimbrite rock. Radial stream networks actively erode the volcanoes and surrounding plains. The central volcanoes Ruapehu, Tongariro and Ngauruhoe are high enough to be almost continually snow-covered, and Ruapehu has some active glaciation. The Taranaki ringplain has a very narrow coastline, mostly comprising cliff-backed beaches of cobble or iron-rich sands. Some limited dune accumulation can be found on the clifftops adjacent to the coast.

### North Island Axial Mountains - NI {#sec-ap-prov-ni .unnumbered}

Steep to precipitous, high greywacke mountains of the North Island Main Divide and associated ranges with strong structural and lithological control of the macro-topography. Narrow ridges, rocky, outcrop-laden upper slopes, and deep V-shaped dendritic valleys are common, with some evidence of glaciation in the southern ranges. The northern mountains include some areas of more subdued terrain with rounded ridges and remnant plateaus.

### Southern and Eastern Sedimentary Hills - NS  {#sec-ap-prov-ns .unnumbered}

Extensive, steep to very steep, strongly dissected hills of soft marine sedimentary rocks. Gentler slopes are covered by ash deposits from nearby stratovolcanoes. Southwest of the axial mountains, the hills have been continually uplifted over a long period but not strongly faulted or faulted, resulting in near-level stratigraphy and a dendritic pattern of linear valleys with sharp ridgelines, fluted sides, and narrow floors. Alluvial infill is not extensive and is usually confined to the lower reaches of major streams, and to areas that have been blocked by major earth movements. Deep-seated slumps and slips are common. Patches of a former land surface can be found as isolated tablelands. Southeast of the axial mountains, the sediments are considerably folded, faulted and crushed, creating considerable landslip hazards.

### Lower North Island lowlands - NM  {#sec-ap-prov-nm .unnumbered}

Flat to strongly rolling downlands, infilled troughs and floodplains on either side of the lower North Island axial ranges. A series of uplifted marine benches and alluvial terraces are covered by extensive quartzo-feldspathic loess deposits (and fine airfall tephra, along the southern Taranaki coastline). The terraces are dissected by major rivers flowing out of the adjacent central ranges. Extensive floodplains are built below the terraces from mixed alluvia originating in the axial mountains and sedimentary hills. On the southwest coast, a large accretionary coastal dunefield reaches from Paraparaumu to Whanganui and contains high dunes, mixed-drainage sandflats, and swamps.

### Southern East Coast Cretaceous sedimentary hills - NA  {#sec-ap-prov-na .unnumbered}

High, steep hills of greywacke and crushed argillite with occasional limestone, considerably deformed and faulted by ongoing tectonic movement. Hills have narrow, sharply defined ridge crests, numerous narrow valleys and restricted areas of rolling land and terraces. Structurally controlled NE-SW trending strike ridges, cuestas and hogsbacks with pronounced dip and scarp slopes feature in some areas capped by more resistant limestones and calcareous sandstones. Steep-sided outcrops (taipos) feature in some areas where massive more competent sandstones and limestones are present.

## South Island {#sec-ap-prov-sil}

### South Island axial mountains - SI  {#sec-ap-prov-si .unnumbered}

Steep, high, glaciated mountains of the South Island Main Divide and associated ranges with strong structural and lithological control of the macro-topography.

### Front Ranges and inland basins - SR {#sec-ap-prov-sr .unnumbered}

Steep to very steep dissected mountain ranges with extensive scree, sharp crested peaks and ridges, and deep colluvial and moraine mantled footslopes, separated by wide braided river valleys and fault controlled inland basins with extensive glacial outwash terraces, moraines, and lakes. Predominantly Torlesse greywacke sandstone and mudstone, and tz II schist of acid-intermediate quartz feldspathic composition.

### Otago basin and range - SO {#sec-ap-prov-so .unnumbered}

Prominent steep-sided and flat to rolling broad-crested ranges with tors, separated by wide deformation controlled flat-floored sediment-filled basins and valleys with extensive glacial moraine, outwash terraces, and recent valley fill. Predominately schist (tz IIa – tz IV) with minor Torlesse sedimentary rocks of acid-intermediate quartzo- feldspathic composition. Tertiary aged sedimentary soft rock inliers incorporating minor alkali to basaltic volcanics underlie the floor floors, with remnants present on ridge crests as outliers and fringe the coastline in places. Extensive loess mantles lower elevation slopes.

### Fiordland - SF {#sec-ap-prov-sf .unnumbered}

Steep to very steep to precipitous alpine and valley slopes with cirque basins, U-shaped valleys, rolling tops, and coastal fiords developed on hard, massive, coarse-grained, crystalline acid to basic igneous and metamorphic rocks, minor Paleozoic sedimentary, calcareous, and ultrabasic rocks all with very shallow, weakly weathered regoliths. Minor Tertiary sedimentary lithologies and valley floor in-fill. 

### West Coast piedmont, hills and mountains - SW {#sec-ap-prov-sw .unnumbered}

Dissected, extensive fluvioglacial outwash terraces, moraine ridges, and marine beach terraces; Recent broad valley floor floodplains, terraces, and fans infilling abandoned glacial troughs; extensive lowland moderately steep to steep hillscapes; and steep, glaciated and intensely fluvially dissected mountain ranges of granite and gneiss, or ancient sedimentary rocks (greywacke) rocks with a drape of less well indurated Cretaceous-Tertiary cover beds in places.

### Northwest Nelson - SN {#sec-ap-prov-sn .unnumbered}

Steep to very steep extensively glaciated mountain ranges with an exhumed peneplain and lithologically controlled topography underlain primarily by hard to very hard heterogenous Paleozoic sedimentary and acid (granitic) igneous and altered volcanics rocks, marble, and the remnants of hard and soft Cretaceous-Cenozoic cover beds. The region includes the deeply weathered Pleistocene gravels of the Moutere depression. 

### Marlborough Sounds and Triassic Mountains - SS {#sec-ap-prov-ss .unnumbered}

Steep to very steep dissected mountains with angular ridges and narrow valleys dominated by indurated quartzofeldspathic sedimentary and lower grade schist rocks \[tz IIa, IIb\]; a belt of ultramafic and associated volcanic rocks characterised by irregular, hummocky topography; and limestones, volcaniclastics, and basalts to the west. Structural and lithological control of the landscape is evident with thick sandstone sequences forming ridge crests, and valley profiles showing strong asymmetry with prominent dip slopes reflecting the regional schistosity.

### Southeast Marlborough Cretaceous Mountains - SM {#sec-ap-prov-sm .unnumbered}

Steep to very steep fault splintered structurally controlled intensively dissected sharp crested mountain ranges with extensive bare rock and scree, rock glaciers and minor cirque basins, and extensive steep to very steep dissected lower mountain and colluvial footslopes, separated by long, straight intermittently terraced valleys and minor intermontane basins. Underlain by acid-intermediate quartzofeldspathic Torlesse greywacke rocks, with minor basic igneous plutons, dikes, and sills; with remnants of Cretaceous-Pliocene covering strata preserved in fault-angle depressions and along the coastal margin.

### East Coast Peninsulas - SP {#sec-ap-prov-sp .unnumbered}

Strongly rolling, moderately steep and steep, dissected collapsed intermediate to basic volcanic peninsulas with bedrock, mixed volcanic bedrock and loess, and loess-dominated colluvium.

### East Coast Plains and Downs - SE {#sec-ap-prov-se .unnumbered}

Extensive, coalescing, broad outwash piedmont fans, aggradational and degradational terraces, lower fan, and low-gradient coastal plain depositional sequences; associated interior basins, and the rolling to strongly rolling to moderately steep hills and downlands underlain by moderately soft and hard young non-calcareous and calcareous rocks, greywacke, and weathered older gravels, with or without a significant loess mantle.

### Southland mountains, hills and plains - SL {#sec-ap-prov-sl .unnumbered}

Steep to very steep glaciated mountains shedding volcanic and basic-quartzofeldsphathic colluvium, moderately steep to steep hills with prominent strike ridges developed on andesitic sedimentary rocks, with an intermittent loess mantle; moderately steep to steep hill country developed on deeply weathered plutonic rocks, and the alluvial landscapes sourced from the Fiordland and Wakatipu glaciers; moraines and extensive coalescing and overlapping alluvial aprons, and suites of outwash terraces, fans and floodplains; coastal Recent and older sand dunes, gravel beach ridges, alluvial lagoonal deltaic flats and extensive peat bogs; and encompassed hard and soft rock cored downlands and hills. Deep loess mantles a significant proportion of all topographies but is thickest on the terraces and rolling downlands.

## Offshore Islands {#sec-ap-prov-oil}

### Stewart Island - OT {#sec-ap-prov-ot .unnumbered}

Steep to very steep mountain slopes with minor cirques and moraines; and strongly rolling to moderately steep, dissected, hill and plateau slopes developed on coarse-grained deeply weathered crystalline granitic- to dioritic plutonic rocks; with steep cliffs interrupted by beaches backed by large sand dune complexes extending inland on the western coastline and the drowned valleys of Paterson Inlet, Port Adventure, Lords River and Port Pegasus on the east; extensive sand plain deposits form gently east-dipping flights of terraces throughout the Freshwater River catchment.

### Chatham Islands - OC {#sec-ap-prov-oc .unnumbered}

Low hills of schist and andesitic tuff, partially covered by uplifted marine sedimentary rocks and intruded by basaltic lavas. Extensive peat-covered lowlands with minor alluvium and coastal sands.

### Subantarctic Islands - OS {#sec-ap-prov-os .unnumbered}

Low, hilly islands bounded by tall, wave-eroded cliffs on the southern continental slope. The islands are mostly volcanic, with some comprising a more complex mix of uplifted greywacke or granite intruded by later volcanics and sometimes partly eroded by glacial conditions. Upper surfaces are often planated and are covered by extensive, deep peats. Low discontinuous terraces may be evident around their coastlines. Many of the smaller outlying islands are too exposed for soil to form. 
