# Observing and sampling soils {#sec-obssamp}

## Exposing the profile {#sec-dig}

The following are general procedures; they may need to be adapted to specific locations. Further discussion of these methods may be found in [@ryan2008; @heck2017; @mantel2023]

### Cleaning an exposure {#sec-dig-exp}

1.  Locate a part of the exposure that is safely accessible. Exposures can change rapidly over short distances, so consider the landscape/landform and which section(s) of the exposure might be most representative.
2.  Trim back or clear overhanging vegetation.
3.  Use a spade to scrape back at least the first few inches of soil, revealing a fresh face approximately 40-50 cm wide. Try to create a roughly vertical face; this may involve excavating 'in' to the exposure surface.
4.  If the exposure is less than 1 m tall, some minor excavation may be required to expose the profile to sufficient depth.
5.  Use a smaller hand tool to finish smoothing back the face (avoid smearing), and then use it to 'pick out' the right-hand half of the face in a way that reveals the soil structure (this last part is optional; soils may be too weakly structured or wet for picking to add value).
6.  For sandy or dusty soils, brush clean the lower parts of the exposure face, which may have become coated with material from upper horizons. This is especially important when sampling.
7.  Anchor a pit tape on the left side of the profile, optionally pinning it at the base.
8.  If the profile is partly or fully dry, spray it down lightly with water to bring up the colours consistently across the whole face.
9.  Photograph the full profile and then zoom in on \~30 cm sections. Optionally, mark the horizon boundaries with pins and take a second whole-profile photo.
10. Proceed with the soil description and sampling.
11. After describing, clean up any spoil, either infilling excavation or sweeping it back out of any adjacent drains.

### Digging a large pit {#sec-dig-bigpit}

::: {#imp-dig .callout-important appearance="minimal" title="Excavation safety"}
Digging large soil pits involves safety risks. Make yourself aware of the advice provided by WorkSafe New Zealand around managing excavations, and your responsibilities [@worksafenewzealand2017].
:::

1.  Pre-screen potential excavations for underground services. Use 'dial before you dig' services and ideally a pipe/cable locator. On farms away from urban services, talk to the landholder about the locations of water supply pipes, gas-line easements and similar.
2.  On flat land, choose a pit orientation that will create optimal lighting conditions on the main face. On sloping land above \~10 degrees, orient the pit against the slope to minimise effort and keep the pit structure safe.
3.  Excavate a large enough area to work in, usually 0.5-1.0 m wide.
    -   Work towards a target depth of 1 m at the main face (or at the very least, the top of the B horizon), leaving steps for access and benching side walls to minimise collapse risk.
    -   Place spoil to one side on a tarpaulin, far enough back from the edge that it won't fall back in. Don't place spoil uphill.
    -   Ideally, separate top and subsoil for refilling.
    -   Avoid compressing or disturbing the surface above the main face.
    -   If it is not safe to dig to the target depth, use an auger to sample beyond the safe depth.
    -   Always stop excavating at the water table.
4.  Clean the main face and prepare it as described for exposures (@sec-dig-exp).
5.  Proceed with the soil description and sampling.
6.  After describing, refill the pit, tamping down spoil to re-create the former surface as closely as possible.

Note that pits deeper than chest height may rapidly become unsafe. Bracing is recommended past 1 m and required past 1.5 m.

### Digging a small pit {#sec-dig-lilpit}

Small pits lack the safety risks of large pits, but locations should still be pre-screened for buried services (see @sec-dig-bigpit).

1.  On flat land, choose a pit orientation that will create optimal lighting conditions on the main face. On sloping land above \~10°, orient the pit against the slope to minimise effort and keep the pit structure safe.
2.  Excavate a small pit \~1 spade-width wide and 3-4 long, to \~0.6 m deep. Ideally the top 5-10 cm of B horizon should be exposed, so deepen the pit slightly if necessary. Place spoil to one side on a tarpaulin.
3.  Where texture and moisture conditions allow: Using the spade, gently excavate a 'slice' of the back pit face 5-10 cm thick. Remove the profile in sections, laying it out on a tarpaulin or mat.
4.  Use a hand auger to pull out the remaining profile to 1.0 m.
5.  Clean up the pit and photograph the inside, with a measuring tape in place. Take horizon depths from the pit face in preference to the extracted profile as they will be more accurate.
6.  Place a tape alongside the extracted profile and take photographs.
7.  Proceed with description and sampling.
8.  Refill the pit, restoring the former ground surface as closely as possible.

### Augering {#sec-dig-aug}

1.  Lay out a tarpaulin or mat to hold the extracted soil.
2.  Use a spade to remove the first 10-20 cm of profile and/or an overlying litter layer. This allows for accurate determination of surface structure, and avoids having to auger through dense surface plant matter (e.g. pasture grasses).
3.  Auger to depth, taking care to remove the soil in small sections without overfilling the auger head.
    -   Check the hole depth with a tape measure every 3-5 extractions, adjusting the extracted soil to match the depth achieved.
    -   Pay attention to the 'feel' of the auger; this may change noticeably as new horizons are encountered or the water table is reached. You may need to adjust the amount of downward pressure in response.
4.  Describe the extracted soil, allowing for parameters that may not be accurately observed using this method.
5.  Refill the auger hole as far as possible. Use a spade to collapse the top of the hole and recreate a firm surface. This is especially important in paddocks containing livestock.

## Sampling the profile {#sec-samp}

### Preparation {#sec-samp-prep}

[Profiles exposed in pits are sampled for laboratory analysis to quantify and extend data recorded in the field. The basic sampling units are usually, but not necessarily soil horizons. Normally, all the horizons described are sampled and labelled with field number, soil name, horizon, and depth limits on the sample bag and a plastic paper label placed in with the sample.]{.milne}

### Sampling for chemical or spectral analysis {#sec-samp-chem}

[The following method is for sampling from a pit. This is often done in conjunction with sampling cores which can be taken from within the same block of soil as the chemistry sample to ensure the closest possible relationship between the samples for chemical and physical analysis.]{.milne}

[At least 1 kg of fine earth ( \< 2 mm) should be collected from each horizon sampled and sealed in a polythene bag.]{.milne}

[If the soil contains fine or medium ( \< 20 mm) gravel, more sample should be collected, to ensure that at least 1 kg of \< 2 mm material is collected. The larger sample is also needed so that an accurate percentage can be measured during the preparation of the sample. If an appreciable quantity of larger stones are present, other techniques are needed (see below) to quantify the stone content and to measure bulk density (core sampling is not possible), and the \< 2 mm sample can be grab-sampled from around the stones.]{.milne}

[The limits of the horizons should be first marked on the face to be sampled as described in Appendix 4. Whenever possible, samples should be taken one below the other from a representative vertical slice that is 200-500 mm wide and extends far enough into the face of the pit to get sufficient soil from the thinnest horizon. If cores for physical analysis are not being taken from the deepest horizon, it is convenient to sample this horizon first, so that it will not be necessary to re-excavate the bottom of the pit. Before sampling the topsoil, any grass or other vegetation should be trimmed off to ground level with a sharp knife. The top horizon is then sampled and all the surplus soil removed from the full width of the slice leaving a clear step before sampling the next horizon. This process is repeated down the profile, with care taken to avoid contamination by material from overlying horizons. The samples can be taken using a spade held level with the lower boundary of the horizon to collect material loosened by a clean trowel or knife.]{.milne}

[Samples are normally taken from the entire thickness of every horizon identified and separately described. If well defined solids of distinct soil material occur within a horizon (e.g. nodules, concretions) their presence and whether or notthat are included in a bulk sample should be recorded (they are normally included). Significant iron and/or humus pans should be treated as horizons and sampled separately. If any apparently homogeneous topsoil horizon more than 25 cm thick, or lower horizon more than 50 cm thick, is identified it should be divided equally and samples taken from each sub-horizon.]{.milne}

[Samples containing particles of soft rock \> 2 mm, concretions or nodules liable to disintegrate when prepared for analysis should be noted and the particulars forwarded to the laboratory with the sample so that special precautions can be taken in its preparation.]{.milne}

### Composite topsoil sampling

[A number of 0-75 mm cores]{.milne} (between 5 and 10) [from around the area of the pit is collected. The purpose of this composite sample is to enable some conclusion to be drawn about the representativeness of the topsoil sampled in the pit. The sample is usually taken from]{.milne} a 300 m\^2 [area with the core taken beside the left foot every]{.milne} few [paces. The corer, however, should not be put through cow 'pats' or any other obviously non- representative materials. Also care must be taken not to cross the soil boundary.]{.milne}

[The composite sample is labelled with the letter 'z'. A sample from the pit to compare with this composite samples is needed. This pit sample should be 0-75 ± 10 mm in depth. If the topsoil falls within these limits, the normal horizon sample (A sample) is adequate for the purpose. If the A horizon thickness is greater than about 15 cm then a subdivision at 7.5 cm is appropriate. However, if the A horizon is between about 9 and 15 cm it is usually sampled in total and an extra 0-7.5-cm sample (labelled 'y') is taken for comparison with the composite (z) sample.]{.milne}

### Sampling for soil physics

-   Reference Soil Carbon sampling protocol for bulk density - method in text has evolved substantially
