---
title: "Changes in the new edition"
editor: visual
format:
  html: 
    number-sections: false
---

## General

-   The structure of the book has been updated and how has four major sections: Soil setting, Soil Profile, Soil Horizons, and Soil Interpretations.
-   Inherently numeric properties are now recorded as numbers; either single measurements, median-plus-range, or low-high range as appropriate. Options for classifying numeric parameters for ease of communication are presented in the Soil Interpretations section.\
    **Rationale:** Numeric data recorded as ranges in the field has limited re-use potential (in that it can't be combined with the same data recorded against other classifications or as numbers) and the ranges have an inherently limited resolution. Many numeric soils parameters have no inherent natural breaks, but patterns in their distribution can emerge in specific landscapes or over certain scales of examination. Recording such data to classes reduces the odds of ever revealing those patterns clearly.
-   Parameters required for the *New Zealand Soil CLassifciation* (NZSC) have been updated where needed in alignment with the simultaneous review of that document
-   Horizon name protocols remain substantially the same, with some updates to bring the schema into alignment with the NZSC

## Soil Setting (formerly 'Site Data')

This section has been loosely structured around the major soil forming factors.

-   **ADD** Chapter [Parent material](ss_04_parent_material.qmd#sec-pm), discussing ways to record geological and lithological information. General commentary on the use of geological maps is included but there is no requirement to record geological map code or similar, due to scale and purpose differences. Two options for lithology recording are presented (NZLRI rock type, NZSC Family Rock Class). The mineralogy classes used in the NZSC are also included as an optional parameter.\
    Some commentary on available research-grade rock type vocabularies is also included. Longer term, the description manual should consider adopting one of these, but they need further development.
-   **ADD** Chapter [Soils](ss_08_soils.qmd#sec-soil), describing additional sources of New Zealand soils knowledge.
-   **UPDATE** 'Location of profile position' to [Location](ss_02_location.qmd#sec-loc) and describe modern methods of recording site location, including elevation.
-   **UPDATE** 'Annual precipitation' to [Climate and Weather](ss_05_climate.qmd#sec-clim), build out a broader discussion of recommended climate and weather parameters, and available data sources.
-   **UPDATE** 'Geomorphic position' to [Geomorphology](ss_03_landscape.qmd#sec-gmph), with a more structured method of geomorphology description.
    -   The 'P', 'S', 'E' scales of examination previously described on p. 12 of @milne1995 are loosely retained as Landscape, Landform and Site, but the details of their expression differ.
    -   Slope and aspect are retained as optional measurements. How they are recorded varies with scale of examination.
    -   Slope length and width are no longer required to be measured in-field, as this is generally impractical and slope width has no inherent relevance to soil character. Options for computation from Digital Elevation Models (DEMs) or measurement in GIS are mentioned.
    -   'Wave length and amplitude' is replaced by the simpler term 'relief' and is only recorded at Landscape scale. The definition is the same. A relief classification is added in @sec-reliefclass.
    -   Assessment of rock outcrop and boulder cover at the site is moved to @sec-pr-surfcov.
    -   Geomorphic word descriptors (p.15-22) have been regrouped into the Landscape/Landform structure the highly local ones been moved to 'natural microrelief', @sec-pr-microrn.
    -   The user is referred to @ncst2024, p. 38-41 for detailed description of drainage channels, if needed. This is optional.
-   **UPDATE** 'Vegetation' to [Biota](ss_06_biota.qmd#sec-biota) to allow discussion of when and how to describe other soil-influencing organisms.
    -   **REMOVE** the vegetation description standard (p. 25-31) and replace with cross-references to appropriate existing standards. The RECCE method is now recommended for high-detail work, and the LUC Vegetation classes for routine assessment. The LCDB can be used for rapid assessment.\
        **Rationale** The measurement standards given don't align with how vegetation is currently recorded by NZ botanists. The 'Atkinson' structural classes in Table 2 are not in common use and have the additional problem of grouping all forests into one category, which has very limited discriminatory power. Soils in NZ are known to be heavily influenced by specific types of past and present forest cover, rednering the scheme suboptimal.
-   **UPDATE** 'Land use and land-management practices' to [Land cover, land use, and land management](ss_07_landuse_mgmt.qmd#sec-lu). The section now suggests using the proposed NZ Land Use Classification [@law2024] for land use and the existing Land Cover Database for land cover. Land management codes have been replaced with a discussion of potential land management practices that may be recorded (no codes are provided). The land management practice codes previously listed on p. 33-34 have been migrated to the following code lists:
    -   Evidence of drainage works affecting the site is now recorded as part of profile drainage assessment (@sec-in-pdrng-alt).
    -   Evidence of localised human alteration to the land surface is now recorded as anthropogenic microrelief (@sec-pr-microra).
    -   Most remaining codes are now recorded as 'recent site disturbances' (@sec-pr-dist).
-   **MOVE** Erosion and deposition from Soil Setting to Soil Profile.

## Soil surface and profile

### The soil site

-   **UPDATE** the definition of a 'soil site' to better interact with the landscape/landform geomorphology description system, and account for the variety of soil sampling methods in use (point, plot, transect, etc). The diameter of the surface examined around most sites is reduced from \~100 m to \~20 m; larger areas should be assessed as Landforms.
-   **MOVE** Chapter 'Reference data' into this section
    -   **ADD** location coordinates as required metadata (@sec-ref-loc, and crosslink to more detailed discussion of requirements in chapter 'Location')
    -   **ADD** Site purpose @sec-ref-why
    -   **ADD** Site selection method @sec-ref-sampstrat
    -   **REMOVE** a requirement for survey title. This is replaced by advocating for a profile identifier that includes a project-level grouping code, and some more generic advice about identifiers.
    -   **REMOVE** requirement for soil series name and classification. These are interpretations, not metadata.
-   **ADD** a non-optional code-set for exposure type (@sec-pr-exptype), documenting the method by which the soil was exposed for assessment (pit, auger etc).
-   **ADD** a requirement to record the maximum depth of observation (or calculate it from horizon depth data)
-   **ADD** a code list for recording the reason a soil profile did not reach 100 cm
-   **ADD** a code list for recording recent site disturbances that have the capacity to impact the soil profile description.
-   **ADD** a 'site setting' subsection, summarising the minimum required data points from the 'soil setting' chapters that should be recorded.

### Soil surface

-   **ADD** site-specific slope and aspect recording instructions. These are not optional, unlike slope and aspect at the broader landform and landscape levels. (@sec-pr-slope, @sec-pr-aspect)
-   **ADD** an assessment of surface cover types, recorded as a compositional set (types observed must add to 100%, see @sec-pr-surfcov). This includes surface stone and outcrop.
-   **ADD** an optional code list for recording recent disturbances to the soil surface.
-   **ADD** an optional code list for recording presence and state of surface water (@sec-pr-surfw)
-   **ADD** an optional code list for recording open surface cracks (@sec-pr-crack)
    -   **ADD** optional code lists for recording natural and anthropogenic microrelief (@sec–pr-micror)
-   **REMOVE** reference to 'fresh' or 'aged' samples [@milne1995, p. 35]; soil descriptions should only be carried out on fresh soil materials.
-   **UPDATE** Separate Erosion/Deposition into two sets of three-part descriptive codes to allow easier recording of distinct processes affecting the surface (@sec-pr-erosion, @sec-pr-deposition). Rapid noting of erosion and deposition can be made using site disturbance codes; these are optional extras that allow a little more detail to be communicated.
    -   **UPDATE** gravity-driven erosion codes for international compatibility
    -   **ADD** subtypes of wind deposition for volcanic ash, sand and silt
    -   **ADD** subtypes of water deposition for flood, storm surge and glacial action

### Defining soil horizons

-   **ADD** a clear statement about the differences between the land surface, the soil surface, and the soil mineral surface
-   **ADD** separate instructions for recording horizon depths, based on whether a large section of profile is visible and on whether detailed assessment is desired (@sec-pr-bdydist)
-   **ADD** guidance on accurately recording horizon boundaries on steep slopes (see @imp-stp)
-   **CHANGE** boundary shape by making 'occluded' its own option rather than a modifier placed on the other four categories. It is also renamed to 'discontinuous'. This improves international compatibility (@sec-pr-bdyshp)
-   **CHANGE** boundary width code 'D - Distinct' to 'C - Clear' to avoid duplicate short codes (D is also used for Diffuse).
-   **ADD** a clear statement about when to switch from recording a diffuse horizon transition to defining a new horizon. 30 cm is the proposed cutoff. (@sec-pr-bdydist)
-   **ADD** a section about how to record infill features (@sec-pr-inf)
-   **REMOVE** Table 3 'soil water state and soil water potential' in favour of using the soil water status codes in Table 4. Applying Table 3 correctly requires a tensiometer and/or laboratory data. The schema in Table 4 aligns more closely with international soil water status description requirements.
-   **ADD** a section on how to record parent materials on a per-horizon basis, including lithology, weathering state, and origin @sec-pr-pm. Note that the existing weathering status schema from Milne has been retained for describing the weathering status of profile rock fragments specifically (see @se-rockfrag-wth) and replaced here with the schema of @juilleret2016, slightly modified. The parent material origin code list has been developed from the schema in @webb2011.

## Soil horizons

### Soil architecture

This section comprises a considerable revision of the 'Macrofabric' section of @milne1995. Components are more clearly separated and options for both rapid and detailed assessment are given.

-   **UPDATE** structure grade to describe a clear gradient of progressively stronger development (Single-grain –\> Massive –\> Weak –\> Moderate –\> Strong). Clearly define apedal/pedal in text.
-   **ADD** structure origin after the proposal of @anderson2024 to distinguish between pedogenic, geogenic, and human-induced structural units. This is optional; not recording it assumes all structures are pedogenic.\
    **Rationale:** adding this parameter allows more effective description of C and R horizon structural characteristics, and more clearly highlights human effects on structure e.g. tillage and compaction.
-   **ADD** structural unit shape 'angular blocky'. Consistent with international standards; useful for the extremely squared-off peds that can be observed in, e.g., Pumice soils.
-   **REMOVE** structural unit shape 'tabular'. Exists in no other system, appears to be a synonym for platy.
-   **REMOVE** structural unit shape 'cylindrical'. Exists in no other system
-   **REMOVE** Figure 8 and 9 flowcharts - redundant
-   **REMOVE** shape options 'botryoidal' and 'stellate' as their utility is unclear
-   **REMOVE** the requirement to measure inclination of all soil macrofabric components
-   Parts of the former Appendix 6 'Procedures for describing macrofacbric' have been moved into this section, providing clear instructions on how to assess structure.
-   **UPDATE** detailed description options for rock fragment shape to align with modern standards (@sec-rockfrag-shp)
-   **UPDATE** root recording to align with the schema in ISO 25177:2019, focusing on counts per 10 sq cm. Counts may be split by size if desired. Root position in the profile should also be recorded.
-   **UPDATE** list of void types to provide simpler options. Rename Krotovina to Tunnel to reduce jargon.
-   **UPDATE** Clearly separate the description of large voids from small pores.
-   **MOVE** description of structural unit surface features, concentrations, and infilled voids to 'Secondary Features'.
-   **ADD** optional detailed description terms for artefacts.
-   **ADD** description options for substrate geogenic features - bedding planes and rock fracture patterns.

### Soil colour

-   **ADD** clear instructions for accurately recording colour in the field, as well as notes about colour vision acuity and the use of technology like colour sensors and cameras
-   **ADD** a direct statement about the definition of the matrix colour, as it differs from most other systems which choose based on areal dominance alone.
-   **ADD** codes for colour pattern type. NB Patterns from mixing by mechanical or biological means are not distinguished as the presence of such disturbances is recorded in several other ways (site disturbance, horizon names, secondary features)
-   **ADD** an optional short-code list for simplified colour recording. This may be applied to patterns and even other soil solids if desired but cannot be used for recording matrix colour(s).

### Soil texture

-   **CHANGE** the recording system to allow texture classes that describe the fine earth, gravel and organic matter content together. The system aligns with NZSC requirements and also with the way texture is recorded in geotechnical work. The boundaries of the fine-earth texture classes and groups remain unchanged, as do the component particle size limits.
-   **ADD** commentary clarifying the differences between hand texture and laboratory particle size analysis
-   **ADD** a table of clay/silt/sand ranges for the NZ texture triangle
-   **UPDATE** the triangle diagram for better visual clarity
-   **ADD** an option for rapid texture assessment, compatible with S-Map and the NZSC
-   **UPDATE** description options for organic materials
-   **UPDATE** description options for rock fragments in a texture context (more detailed description is also possible using @sec-rockfrag
-   **REMOVE** the von Post scale for organic matter decomposition

### Secondary features

-   **ADD** options for detailed descriptions of pans
-   **UPDATE** description of concentrations to allow rapid or detailed assessment
-   **UPDATE** code lists for concentrations, pans, coatings and pressure features to separate the various concepts more clearly and provide rapid and detailed assessment options for both.
-   **ADD** a note about distinguishing pedogenic lamellae and geogenic lamina as well as when and how to describe them in a profile
-   **ADD** a subsection on cryofeatures. No new code lists or criteria are defined at this point due to lack of available profile data, but the section points to other parts of the standard that may be used to highlight cryofeatures in a profile morphology description. These align with the new NZSC appendix on Cryic Soils.

### Consistence tests

-   **ADD** infobox discussing which tests may be required when classifying against the NZSC
-   Consistence tests have been re-written with clear, step by step instructions. The evaluation criteria are unchanged, except for the following:
-   **REMOVE** reference to the use of handheld penetrometers and Singleton blades, as these are no longer common practice. Notes about their origin and previous use are retained to give context to legacy literature.

### Field tests

-   Chemical field tests have been rewritten with clear, step by step instructions and are accompanied by equipment lists and improved safety warnings.
-   **ADD** infobox discussing which tests may be required when classifying against the NZSC
-   **REMOVE** instructions for sand content by boiling oxalate, P-retention, and organic properties; these should be done in the laboratory.

## Soil Interpretations

### Horizon notation

-   Horizon naming conventions are largely unchanged, but the structure of the section has been rearranged and some wording updates have been made to many definitions to align them better with the NZSC
-   **CHANGE** 'L' horizon name from describing fresh leaf litter to describing organic horizons developing under largely unsaturated conditions (this replaces both F and H). This allows a parallel set of horizons to those used for peats (Lf, Lh, Lm) and aligns more closely with the texture code system. The former F horizon would now be recorded as 'Lm' and H as 'Lh'. 'Lf' is effectively a new option for organic material that is no longer fresh but still little-decomposed, most likely due to having a high fibre and/or lignin content (e.g. palm fronds). Fresh litter presence at a site is now noted using the surface cover codes (@sec-pr-surfcov).
-   **ADD** example profile descriptions demonstrating the use of lithological discontinuity codes and the buried horizon prefix.
-   **ADD** a prefix 'e' for signifying Anthropic horizons. Guidance for use is in @sec-hzn-an.
-   **REMOVE** horizon Cu - 'u' considered redundant.
-   **CHANGE** 'e' suffix to 'u' for Fluid horizons and remove reference to 'unripe' concept

### Profile behaviour

This is a new section, containing the former Appendices 1 and 2 (reformatted for clarity), as well as:

-   **ADD** assessment of horizon-level drainage class to underpin profile-level summaries and allow more detailed drainage data to be recorded
-   **ADD** instructions for assessing permeability on a per horizon and per profile level. This system is aligned with permeability as it is defined in @webb2011 for the soil Family
-   **ADD** instrutions for identifying and recording rooting depth restrictions. This system is aligned with root barriers as they are used in S-Map but includes some more specific options

### The New Zealand Soil Classification

-   This is a new section, connecting parts of the description standard to where they might be needed to support a soil classification. Features required to classify the soil are listed and cross-linked down to Sibling level.

## Appendices

-   Appendices 1, 2, 10, 11 and 12 have been moved into the main body of the document
-   Appendices 3-9 are considerably out of date in places and may no longer reflect standard field practice. Interest in updating their content is being canvassed through the external review process.
-   **NEW** Appendix A - recommended field equipment - for excavation, measurement, small hand tools etc
-   **NEW** Appendix B - recording data in the field. Some general commentary about paper and computers.
    -   **New** advice on taking effective field photographs
    -   **New** example data sheets (previously in the back of the document)
-   **NEW** Appendix C - sampling guidance. Some parts of Appendix 9 have been moved in here. Guidance for exposing the profile and setting it up for description using different equipment is included, along with common sampling protocols for profiles and surface bulks. A sampling layout design for monitoring is included which aligns with the method currently used for .
-   **NEW** Appendix D - data model. Diagrams of how the data points in the document fit together in a relational database model; clear indications of must-have and nice-to-have parameters.
-   **NEW** Appendix E - Classifying numeric measures. Contains classification schema that are commonly applied to various numeric parameters (slope, aspect, relief, abundance, size)
-   **NEW** Appendix F - correlations. Shows how the standard can be worked in with other land assessment systems used in NZ.
-   **NEW** Appendix G - Land provinces. Contains the extended definitions of provinces listed in @sec-gmph-prov.
