# Secondary features

-   define
-   abundance charts (re-use wrb fig 8.1.2)

## Redoximorphic features

-   record abundance relative to whole soil mass in percentage increments of 5-10%

### Feature development

-   influenced by water regime and time
-   ordered category
    -   D, M, C, N, P

### Feature colour

-   inference to groups of minerals, can't narrow it down too much
-   o, d, y, n

### Translations

-   existing systems have a larger set of codes to describe the same phenomenon (mottles, segs, pans)
-   examples
    -   soft jarosite mottles and ferrihydrite/goethite breakdown products in a ripened AASS
        -   20Mn, 10My with low chroma matrix
    -   jarosite mottles in an AASS that otherwise remains reduced
        -   10My with low chroma matrix
    -   iron oxidation products in imperfectly drained loess
        -   40Mo with low-medium chroma matrix
    -   WRB ferric horizon
        -   20Co
    -   WRB petroplinthic horizon
        -   70Po
    -   WRB pisoplinthic horizon
        -   50Nn
    -   moderately well drained horizon with some slight mottling
        -   05Mo, 01Md
    -   well drained horizon with some slight mottling
        -   01Mo

more than x percent implies y degree of cementation. 85%+ = pan?

Note: these features define a soil horizon and thus thickness is already described. As such, a WRB ferric horizon would have to be at least 15cm thick in addition to having the character described above.

## Precipitation features

-   crystals and masses - halite, gypsum, carbonate, silica
-   from upward vs downward solute+water movement (?)
-   progression of concs/nodes to pans

## Illuviation features

-   lamellae
-   clay coats
-   cutans and other infill types
-   fragipans (???)

## Stress features

-   pressure faces, slickensides, things of that nature

## Cryogenic features

-   for alpine areas and antarctic soils

Unresolved - wrb gets quite focused on distinguishing coarse frags and pans from broken up remnants of more complete indurated layers comprised of secondary material. Relevance unclear particularly in NZ
