# Consistence

-   context and use
-   note that some of these assessments can only be reliably conducted on undisturbed samples of soil, which usually rules out cored or augered samples
    -   need alternatives for those?
-   how to sample for these tests
-   may need to complete assessments post-field
-   expected accuracy vs lab tests (low)

## Cohesive vs non Cohesive

-   test instructions, cross link to remoulding, dilatency and plasticity tests (these are moved up front as well)
-   Note: that flow chart in fig 13 can literally just be a table
-   talk about dry coherence test here rather than 10 pages later

## Remoulding

-   currently missing clear instructions

## Plasticity

-   test instructions
-   interpretation

## Stickiness

-   (moving up because easy to do right after plasticity test)
-   instructions
-   interpretation

## Dilatency

-   test instructions
-   interpretation

## Thixotropy

-   instructions
-   interpretation

## Penetration resistance

-   reconcile with unconfined strength
-   moving up to before other tests as an undisturbed face is required
-   what do we keep? Small penetrometer accuracy questionable (add refs), not commonly used at present - but Table 16 requires no gear

## Particle Packing

-   non-cohesive soils
-   do we keep all of this or just T19?

## Unconfined strength

-   more clear distinction that two types of strength may be apparent (soil mass, individual peds)
-   test instructions
-   use of a pinch gauge for hand strength calibration (Drohan et al, 2020)
-   interpretation
    -   SMap specific information
-   T13 (reconcile with WRB field guide - looks almost identical)

### Remoulded strength

-   instructions

### Strength at plastic limit

-   do we keep this?

### Sensitivity

-   ratio of natural to remoulded
-   instructions
-   when not to bother
-   interpretation

## Mode of failure

-   link more clearly to NZSC
    -   cutanoxidic horizon - behaviour varies significantly with water content
    -   fragipan - requires brittle failure when moist
    -   organic material - deformable in field condition
    -   Oxidic - consistently friable across moisture states

## Fluidity

-   clearer statement that this test is for field-saturated soils only
-   and that it effectively tests whether subaqueous deposition was the mode of emplacement
-   instructions
-   interpretation

## Induration

-   instructions
-   interpretation
-   NB not a field test
