# Horizons

A soil horizon is a distinct layer within a soil profile. Horizons are distinguished by differences in texture, stoniness, structure, colour, consistence or other soil properties as described in this section. Delineated horizons should ideally represent depth intervals over which important soil attributes change minimally. Conversely, the horizon boundaries should represent depth intervals over which there is a relatively high rate of change of important soil properties.

Not all important soil properties change from one horizon to the next or at the same rate with depth. In some instances confident interpretation of the suitability of a soil for a particular end use may depend on the rate of change of a single property at a horizon boundary. For this reason the basis for separating the horizon may need to be explicitly stated, not just the traditional generalised estimate of the amount of overall change. 

## Depth and Thickness




## Boundary shape

## Boundary distinctness

note: when to make a new horizon note: names at the end - need supporting data to define

## In situ moisture content

- at time of obs
- table 4 not table 3 - reconcile with WRB Table 8.28
- discussion of field vs lab measurement
