# Soil texture

-   size domain
-   clearly explain how fine earth fractions are compositional, but so is fine earth + coarse fraction
-   example of how to adjust to get a full composition

## Fine earth

### Perceived texture

-   discussion of difference between percieved texture and PSD by lab analysis
-   influence of non-mineral components - OM, water
-   influence of particle mineralogy, particularly clay
-   influence of particle shape

### Particle size estimate

-   how to (refer to literature)
-   recording on a triangle
-   mean/sd of sand/silt/clay

note: influence of size fraction divisions

## Coarse minerals

-   record presence, abundance to nearest 5-10%
-   record modal, min and max size - measure on longest dimension
-   optional roundedness
-   optional lithology
-   still need to think more about how to structure this
-   note: shape not much use without in situ orientation

## other coarse components

### natural

-   shell, bone, charcoal, timber

### artefacts

-   per WRB list (maybe compress a little)
