---
title: "Horizon Properties"
editor: visual
---


## Permeability ratings

-   as currently used - import from S-Map manual

## Drainage

Soil drainage is an assessment of how fast water leaves a soil profile relative to supply. This characteristic can be controlled by morphological characteristics that occur in a range of combinations.

Drainage should first be assessed on a per-horizon basis. These interpretations are later summarised at a profile level (see @sec-in-pdrng). @tbl-in-intdrng below summarises the common characteristics associated with each horizon drainage class. A 'balance of evidence' approach should be taken when assigning a drainage class to a horizon. When in doubt, choose the poorest class available.

[NB: Still working out the details here!!]{style="background-color:orange"}

```{r}
#| label: tbl-in-intdrng
#| tbl-cap: "Internal drainage - horizon characteristics"
#| column: page

dat_in_intdrng <-
  tribble(~Code, ~Name, ~HNames, ~sws, ~mcol, ~Mottles, ~Texture, ~StrGr, ~secfts, ~cons, ~Roots, ~voids,
          'VP', 'Very poor', 'O*, *r', 'Saturated or wet', 'Dark or gley', 'None to Few (<10%)', 'Peaty, clayey, silty. Rarely sandy, very rarely stony', 'Apedal', 'Few to None', 'Deformable', 'None', 'None',
          'PO', 'Poor', '*r, *g', 'Wet', 'Dark, gley or grey', 'None to Few (<10%)', 'Clayey, silty, occasionally peaty and more often just highly organic (e.g. drained ex-peat). Rarely sandy, very rarely stony', 'Apedal to weak', 'Few to none', 'Deformable or semi-deformable',  'Few to None', 'Few',
          'IP', 'Imperfect', '*(g)', 'Moist to slightly moist', 'Dark, grey, yellow or pale', 'Abundant to Profuse (50 - >75%)', 'Any',  'Apedal to moderate', 'Nodules and/or pans', 'Friable to semi-deformable', 'Few to common', 'Few to common',
          'MW', 'Moderately Well', '*(f)', 'Moist to Dry', 'Any non-gley', 'Few to Many (2-%) and non-gley', 'Variable but usually not clayey', 'Any', 'Nodules', 'Very friable to brittle',  'Common to Many', 'Common to Many',
          'WE', 'Well', 'No redox suffixes', 'Moist to Dry', 'Any non-gley', 'None', 'Variable but usually not clayey', 'Any', 'Very Few to None (<2%) and non-gley', 'Very friable to brittle', 'Common to Many', 'Common to Many')

tbl_in_intdrng <- gt(dat_in_intdrng) |>
   tab_options(
    column_labels.font.weight = 'bold', 
    heading.title.font.weight = 'bold',
    table.align = 'center',
    table.width = '85%'
  ) |>
  tab_style(style = list(cell_text(color = 'red', weight = 'bold')),
            locations = cells_body(columns = 1)) |>
  tab_style(style = list(cell_text(weight = 'bold')),
            locations = cells_body(columns = 2)) |>
  cols_label(HNames = 'Horizon Names',
             sws    = 'Soil Moisture',
             mcol   = 'Matrix colour',
             StrGr  = 'Structure Grade',
             secfts = 'Secondary features',
             cons   = 'Consistence',
             voids  = 'Voids/cracks')

tbl_in_intdrng
```

::: callout-note
note here about the 'somewhat poor' concept and why its not included yet
:::

::: callout-note
note here about the difference between wet soils and wet-and-anoxic soils, crosslink to field tests
:::
