# Horizon properties

- some numerical properties are specific to a single soil feature and have a classification associated in text
- more general physical properties have multiple potential classifications, and none are globally accepted. Multiple options are presented below. These should not be used in the field.

## Numerical classifications

### Size classes

- use the particle size divisions
- talk about international differences

### Abundance classes

- commonly boil down to 'barely appreciable', 'rare', 'common', 'abundant'
- think moar

---

## Conventional horizon names

- support for NZSC level one-three (four??)
- profile position, major processes, significantly developed features

### Primary Divisions

### Secondary Divisions

### Suffixes

- can theoretically automate if supporting parameters are described in db

### Prefixes

------------------------------------------------------------------------

## Functional horizon names

-   link to NZSC level 5
-   physical/water movement focus missing from conventional system
-   so, complementary
-   more directly derived - so can theoretically automate if inputs are present

### Names

### Components

### Permeability ratings
