# The New Zealand Soil Classification {#sec-nzsc123}

Classifying a profile according to the first three levels of the NZSC [@hewitt2024] requires the following steps:

1.  Identify diagnostic features
2.  Follow the Key to Soil Orders
3.  Follow the Keys to Group and Subgroup.

To extend the classification to levels 4 and 5, the profile form must be identified, key features summarised, and a functional horizon sequence assigned [@webb2011]. This section highlights the elements of the *Soil Description Handbook* that may be required to complete these tasks.

## Identifying Diagnostic features {#sec-in-nzscdiags}

The descriptive parameters that help define the NZSC Diagnostic features are outlined in @tbl-nzsc-diags; see @hewitt2024 for the full definitions. Any or all of the listed parameters may be required for a confident identification.

+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Diagnostic feature              | Identification requirements                                                                                                                                                                                                                                                                                                     |
+:================================+:================================================================================================================================================================================================================================================================================================================================+
| **Horizons, pans and layers**   |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Argillic horizon                | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist)                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec) (relative to overlying horizon)                                                                                                                                                                                                                                                   |
|                                 | -   [Coatings](hr_04_secondary_features.html#sec-hr-coat) or [concentrations](hr_04_secondary_features.qmd#sec-hr-conc) (lamellae)                                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Brittle-B horizon               | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Roots](hr_01_architecture.html#sec-root)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail)                                                                                                                                                                                                                                                  |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Calcareous horizon              | -   Calcium carbonate [concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                  |
|                                 | -   Field test: [Calcium carbonate](hr_06_chemical_properties.html#sec-ft-ca)                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cutanic horizon                 | -   [Coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                                                                                                       |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cutanoxidic horizon             | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail), [stickiness](hr_05_physical_properties.html#sec-cn-sti), [plasticity](hr_05_physical_properties.html#sec-cn-pla)                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Densipan                        | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                                                                                             |
|                                 | -   Field test: [Slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Distinct topsoil                | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix) (relative to deeper horizon)                                                                                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Duripan                         | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Field test: [Reaction to HCl](hr_06_chemical_properties.html#sec-ft-ca), [slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Eluvial horizon                 | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fragipan                        | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Roots](hr_01_architecture.html#sec-root)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail), [unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                              |
|                                 | -   Field test: [Slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Humus-pan                       | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail), [unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ironstone-pan                   | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist) (upper)                                                                                                                                                                                                                                                    |
|                                 | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Consistence: [Induration](hr_05_physical_properties.html#sec-cn-ind)                                                                                                                                                                                                                                                        |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Nodular horizon                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc)                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ortstein-pan                    | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist) (upper)                                                                                                                                                                                                                                                    |
|                                 | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                                                                                             |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Oxidic Horizon                  | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [ped strength](hr_05_physical_properties.html#sec-cn-stra), [mode of failure](hr_05_physical_properties.html#sec-cn-fail), [stickiness](hr_05_physical_properties.html#sec-cn-sti), [plasticity](hr_05_physical_properties.html#sec-cn-pla) |
|                                 | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf), [slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Peaty topsoil                   | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Placic horizon                  | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist) (upper and lower)                                                                                                                                                                                                                                          |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   Consistence: [Induration](hr_05_physical_properties.html#sec-cn-ind)                                                                                                                                                                                                                                                        |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Podzolic-B horizon              | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Coatings](hr_04_secondary_features.html#sec-hr-coat) and [concentrations](hr_04_secondary_features.html#sec-hr-conc)                                                                                                                                                                                                       |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru)                                                                                                                                                                                                                                              |
|                                 | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf)                                                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Redox-mottled horizon           | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reductimorphic horizon          | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slowly permeable layer          | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weathered-B horizon             | -   [Matrix colour](hr_02_colour.html#sec-col-matrix) (relative to deeper layers)                                                                                                                                                                                                                                               |
|                                 | -   [Structure](hr_01_architecture.html#sec-hr-stru) (relative to deeper layers)                                                                                                                                                                                                                                                |
|                                 | -   Evidence of carbonate loss (relative to deeper layers)                                                                                                                                                                                                                                                                      |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Soil materials and contacts** |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allophanic soil material        | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf)                                                                                                                                                                                                                                                                |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [sensitivity](hr_05_physical_properties.html#sec-cn-sens), [stickiness](hr_05_physical_properties.html#sec-cn-sti)                                                                                                                          |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Anthropic soil material         | -   [Artefacts](hr_01_architecture.html#sec-hr-artef) and/or [plastics](hr_01_architecture.html#sec-hr-plas)                                                                                                                                                                                                                    |
|                                 | -   [Recent site disturbances](pr_00_intro.html#sec-pr-dist)                                                                                                                                                                                                                                                                    |
|                                 | -   [Landform](ss_03_landscape.html#sec-gmph-lfm) (Human-induced)                                                                                                                                                                                                                                                               |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lithic contact                  | -   Substrate rock presence                                                                                                                                                                                                                                                                                                     |
|                                 | -   Horizon degree of weathering                                                                                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Organic soil material           | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail)                                                                                                                                                                                                                                                  |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Paralithic contact              | -   Substrate rock presence                                                                                                                                                                                                                                                                                                     |
|                                 | -   Horizon degree of weathering                                                                                                                                                                                                                                                                                                |
|                                 | -   [Roots](hr_01_architecture.html#sec-root)                                                                                                                                                                                                                                                                                   |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Saline soil material            | -   Field test: [Electrical conductivity](hr_06_chemical_properties.html#sec-ft-ec)                                                                                                                                                                                                                                             |
|                                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                                    |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sulfidic soil material          | -   Field test: [pH in water](hr_06_chemical_properties.qmd#sec-ft-phfw) and [pH in hydrogen peroxide](hr_06_chemical_properties.qmd#sec-ft-phfox)                                                                                                                                                                              |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sulfuric soil material          | -   Field test: [pH in water](hr_06_chemical_properties.qmd#sec-ft-phfw)                                                                                                                                                                                                                                                        |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat) (especially jarosite)                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tephric soil material           | -   [Lithology](ss_04_parent_material.html#sec-pm-lith)                                                                                                                                                                                                                                                                         |
|                                 | -   [Mineralogy](ss_04_parent_material.html#mineralogy)                                                                                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Vitric soil material            | -   [Rock fragments](hr_01_architecture.html#sec-rockfrag)                                                                                                                                                                                                                                                                      |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   [Lithology](ss_04_parent_material.html#sec-pm-lith)                                                                                                                                                                                                                                                                         |
|                                 | -   [Parent material origin](hr_00_intro.html#parent-material-origin)                                                                                                                                                                                                                                                           |
|                                 | -   [Mineralogy](ss_04_parent_material.html#mineralogy)                                                                                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile forms**               |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gley profile form               | -   [Horizon depths](pr_02_layers.html#sec-pr-depths)                                                                                                                                                                                                                                                                           |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   Field test: [Reducing conditions](hr_06_chemical_properties.qmd#sec-ft-rdx)                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mottled profile form            | -   [Horizon depths](pr_02_layers.html#sec-pr-depths)                                                                                                                                                                                                                                                                           |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Soil features**               |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fluvial features                | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist)                                                                                                                                                                                                                                                            |
|                                 | -   [Rock fragments](hr_01_architecture.html#sec-rockfrag)                                                                                                                                                                                                                                                                      |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Fluidity](hr_05_physical_properties.html#sec-cn-flu)                                                                                                                                                                                                                                                          |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Perch-gley features             | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                                    |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sodic features                  | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   Field test: [Dispersion](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                                                                        |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Other differentiae**          |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Childs' Test                    | -   Field test: [Reducing conditions](hr_06_chemical_properties.qmd#sec-ft-rdx)                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Low-chroma colours              | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reactive-aluminium test         | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf)                                                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Redox segregations              | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc)                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Description requirements for NZSC Diagnostic Features [@hewitt2024] {#tbl-nzsc-diags .striped .hover tbl-colwidths="\[40, 60\]"}

## Following the Key to Orders {#sec-in-nzsc1}

In addition to the diagnostics above, successful navigation of the Key may require documentation of the parameters listed in @tbl-nzsc-key:

+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Order            | Requirement                                                                                                                                                                                           |
+:=================+:======================================================================================================================================================================================================+
| Organic Soils    | -   Layers: [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gley Soils       | -   Layers: [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                       |
|                  | -   Texture: [Texture class](hr_03_texture.qmd#sec-hr-eatxt) (of unconsolidated substrate)                                                                                                            |
|                  | -   Consistence: [Fluidity](hr_05_physical_properties.html#sec-cn-flu)                                                                                                                                |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ultic Soils      | -   Architecture: [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                    |
|                  | -   Colour: [Matrix value](hr_02_colour.qmd#sec-col-matrix) (upper B horizon)                                                                                                                         |
|                  | -   Texture: [Texture group and class](hr_03_texture.qmd#sec-hr-eatxt), [clay content](https://manaakiwhenua.github.io/NZ_soildesc_2024/hr_03_texture.html#sec-tex-pse) (relative to silt)            |
|                  | -   Secondary features: [Coatings](hr_04_secondary_features.qmd#sec-hr-coat)                                                                                                                          |
|                  | -   Consistence: [Unconfined strength](hr_05_physical_properties.qmd#sec-cn-stru) under moist conditions                                                                                              |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
|                  | -   Total depth of soil materials                                                                                                                                                                     |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Podzol Soils     | Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                           |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allophanic Soils | -   Layers: [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pumice Soils     | -   Layers: [Horizon thickness and lower depths](pr_02_layers.qmd#sec-pr-depths)                                                                                                                      |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Melanic Soils    | -   [Lithology](ss_04_parent_material.html#sec-pm-lith) (fine and coarse mineral fractions)                                                                                                           |
|                  | -   Site surface: [Surface cracking](pr_01_surface.html#sec-pr-crack)                                                                                                                                 |
|                  | -   Architecture: [Structure](hr_01_architecture.html#sec-hr-stru), [rock fragment content](hr_01_architecture.html#sec-rockfrag) and [degree of weathering](hr_01_architecture.qmd#sec-rockfrag-wth) |
|                  | -   Colour: [Matrix value](hr_02_colour.html#sec-col-matrix) (A horizon, upper B horizon)                                                                                                             |
|                  | -   Texture: [Texture class](hr_03_texture.html#sec-tex-rec)                                                                                                                                          |
|                  | -   Consistence: [Stickiness](hr_05_physical_properties.html#sec-cn-sti)                                                                                                                              |
|                  | -   Field test: [Calcium carbonate](hr_06_chemical_properties.html#sec-ft-ca), [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                        |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Semiarid Soils   | -   Texture: [Texture class](hr_03_texture.html#sec-tex-rec)                                                                                                                                          |
|                  | -   Field test: [Calcium carbonate](hr_06_chemical_properties.html#sec-ft-ca), [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                        |
|                  | -   Laboratory data: Phosphate retention (low)                                                                                                                                                        |
|                  | -   Layers: [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Oxidic Soils     | -   Layers: [Horizon lower depth](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                     |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Granular Soils   | -   Architecture: [Structure](hr_01_architecture.html#sec-hr-stru), [rock fragment content](hr_01_architecture.html#sec-rockfrag) and [degree of weathering](hr_01_architecture.qmd#sec-rockfrag-wth) |
|                  | -   Texture: [Texture group](hr_03_texture.html#sec-tex-rec)                                                                                                                                          |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pallic Soils     | -   Architecture: [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                    |
|                  | -   Colour: [Matrix colour](hr_02_colour.html#sec-col-matrix) (below the A horizon)                                                                                                                   |
|                  | -   Secondary features: [Coatings](hr_04_secondary_features.qmd#sec-hr-coat)                                                                                                                          |
|                  | -   Field test: [Dispersion](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                              |
|                  | -   Laboratory data: Phosphate retention (low)                                                                                                                                                        |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Brown Soils      | -   Colour: [Matrix colour](hr_02_colour.html#sec-col-matrix) (below the A horizon)                                                                                                                   |
|                  | -   Texture: [Texture group](hr_03_texture.html#sec-tex-rec)                                                                                                                                          |
|                  | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf) (at least moderate)                                                                                                                  |
|                  | -   Laboratory data: Phosphate retention (at least moderate)                                                                                                                                          |
|                  | -   Layers: [Horizon lower depth](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                     |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Anthropic Soils  | Evidence of profile truncation or filling (compare site with surrounding landform(s))                                                                                                                 |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Recent Soils     | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                  |
|                  | -   Consistence: [Fluidity](hr_05_physical_properties.html#sec-cn-flu)                                                                                                                                |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Raw Soils        |                                                                                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Additional description requirements for NZSC Key to Orders [@hewitt2024] {#tbl-nzsc-key .striped .hover tbl-colwidths="\[40, 60\]"}

## Completing the classification to Subgroup level {#sec-in-nzsc23}

At the Group and Subgroup levels of the classification, requirements become more uniform. For example, the majority of Orders need pH data to identify acidic subgroups. Additional requirements are listed in @tbl-nzsc-gsg below.

+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Order            | Requirement                                                                                                                                                                                           |
+:=================+:======================================================================================================================================================================================================+
| Organic Soils    | -   Texture: Organic matter [decomposition state](hr_03_texture.qmd#sec-tex-orgmod)                                                                                                                   |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gley Soils       | -   Texture: [Texture group](hr_03_texture.qmd#sec-hr-eatxt)                                                                                                                                          |
|                  | -   Architecture: [Structure](hr_01_architecture.qmd#sec-hr-stru), [rock fragment content](hr_01_architecture.qmd#sec-rockfrag)                                                                       |
|                  | -   Secondary features: [Concentrations](hr_04_secondary_features.qmd#sec-hr-conc), [coatings](hr_04_secondary_features.qmd#sec-hr-coat)                                                              |
|                  | -   Consistence: [Stickiness](hr_05_physical_properties.qmd#sec-cn-sti)                                                                                                                               |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
|                  | -   [Buried horizons](in_01_horizon_names.html#sec-hzn-bur)                                                                                                                                           |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ultic Soils      | -   Architecture: [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [lithology](ss_04_parent_material.qmd#sec-pm-lith)                                                                 |
|                  | -   [Matrix colour](hr_02_colour.qmd#sec-col-matrix)                                                                                                                                                  |
|                  | -   Secondary features: [Coatings](hr_04_secondary_features.qmd#sec-hr-coat)                                                                                                                          |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
|                  | -   Laboratory data: Exchangeable cations                                                                                                                                                             |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Podzol Soils     | -   Architecture: [Structure](hr_01_architecture.qmd#sec-hr-stru)                                                                                                                                     |
|                  | -   Texture: [Texture class](hr_03_texture.qmd#sec-hr-eatxt)                                                                                                                                          |
|                  | -   Consistence: [Unconfined strength](hr_05_physical_properties.qmd#sec-cn-stru), [penetration resistance](hr_05_physical_properties.qmd#sec-cn-pres)                                                |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allophanic Soils |                                                                                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pumice Soils     | -   Architecture: [Roots](hr_01_architecture.qmd#sec-root), [rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [lithology](ss_04_parent_material.qmd#sec-pm-lith)                       |
|                  | -   [Matrix colour](hr_02_colour.qmd#sec-col-matrix)                                                                                                                                                  |
|                  | -   Consistence: [Unconfined strength](hr_05_physical_properties.qmd#sec-cn-stru), [packing](hr_05_physical_properties.qmd#sec-sn-pack), [mode of failure](hr_05_physical_properties.qmd#sec-cn-fail) |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Melanic Soils    | -   Laboratory data: Exchangeable cations, phosphate retention                                                                                                                                        |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Semiarid Soils   | -   [Matrix colour](hr_02_colour.qmd#sec-col-matrix)                                                                                                                                                  |
|                  | -   Architecture: [Structure](hr_01_architecture.qmd#sec-hr-stru), [rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [degree of weathering](hr_01_architecture.qmd#sec-rockfrag-wth)   |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Oxidic Soils     | -   Texture: [Texture class](hr_03_texture.qmd#sec-hr-eatxt)                                                                                                                                          |
|                  | -   Architecture: [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag)                                                                                                                        |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Granular Soils   | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pallic Soils     | -   Architecture: [Structure](hr_01_architecture.qmd#sec-hr-stru), [rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [degree of weathering](hr_01_architecture.qmd#sec-rockfrag-wth)   |
|                  | -   Secondary features: [Induration](hr_05_physical_properties.qmd#sec-cn-ind)                                                                                                                        |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Brown Soils      | -   Architecture: [Structure](hr_01_architecture.qmd#sec-hr-stru), [rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [degree of weathering](hr_01_architecture.qmd#sec-rockfrag-wth)   |
|                  | -   Secondary features: [Induration](hr_05_physical_properties.qmd#sec-cn-ind)                                                                                                                        |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
|                  | -   Laboratory data: Bulk density, exchangeable cations                                                                                                                                               |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Anthropic Soils  | -   Land use history (Truncated and Mixed Groups)                                                                                                                                                     |
|                  | -   Laboratory data: Bulk density (Compacted Subgroup)                                                                                                                                                |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Recent Soils     | -   Architecture: [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [lithology](ss_04_parent_material.qmd#sec-pm-lith)                                                                 |
|                  | -   Texture: [Texture class](hr_03_texture.qmd#sec-hr-eatxt)                                                                                                                                          |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                                                                                       |
|                  | -   Soil temperature (mean annual)                                                                                                                                                                    |
|                  | -   Evidence of past burial events (e.g. flood deposition)                                                                                                                                            |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Raw Soils        | -   Architecture: [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) and [lithology](ss_04_parent_material.qmd#sec-pm-lith)                                                                 |
|                  | -   Texture: [Texture class](hr_03_texture.qmd#sec-hr-eatxt)                                                                                                                                          |
|                  | -   Consistence: [Fluidity](hr_05_physical_properties.qmd#sec-cn-flu)                                                                                                                                 |
|                  | -   Soil temperature (mean annual)                                                                                                                                                                    |
|                  | -   [Surface water](pr_01_surface.qmd#sec-pr-surfw)                                                                                                                                                   |
|                  | -   [Parent material origin](pr_02_layers.qmd#sec-pr-orig)                                                                                                                                            |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Additional potential description requirements for NZSC Groups and Subgroups, by Order [@hewitt2024] {#tbl-nzsc-gsg .striped .hover tbl-colwidths="\[40, 60\]"}

## Completing the classification to Sibling level {#sec-in-nzscfamsib}

Detailed requirements for classifying the Family and Sibling are contained in @webb2011.

### Family requirements {#sec-in-nzscfam}

+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| Parameter                               | Requirements                                                                                                               |
+:========================================+:===========================================================================================================================+
| Soil Profile Material                   | -   [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) (either texture code or percentage estimate)              |
|                                         | -   [Rock fragment roundedness](hr_01_architecture.qmd#sec-rockfrag-shp)                                                   |
|                                         | -   Depth to [regolithic or saprolithic material](pr_02_layers.qmd#sec-pr-wdeg), if encountered                            |
|                                         | -   Depth to lithic or paralithic contact, if encountered                                                                  |
|                                         | -   Thickness of organic soil material, if encountered                                                                     |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| Rock class of profile stone and bedrock | -   [Lithology](ss_04_parent_material.qmd#sec-pm-lith) of rock fragments (if encountered)                                  |
|                                         | -   [Lithology](ss_04_parent_material.qmd#sec-pm-lith) of substrate non-soil materials (if encountered)                    |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| Rock class of fines                     | Originating [lithology](ss_04_parent_material.qmd#sec-pm-lith) of soil materials \<2mm                                    |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| Texture group class                     | [Texture class](hr_03_texture.qmd#sec-hr-eatxt) of all horizons to 60cm depth or the limit of soil material, if shallower |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| Permeability class                      | [Profile permeability](in_02_interpreted_properties.qmd#sec-in-pperm) class                                                |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------+

: Parameters required to identify the NZSC Family {#tbl-nzsc-famid .striped .hover tbl-colwidths="\[40, 60\]"}

### Sibling requirements {#sec-in-nzscsib}

+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Parameter                          | Requirements                                                                                                                                              |
+:===================================+:==========================================================================================================================================================+
| Soil depth (easily diggable depth) | -   [Horizon thicknesses](pr_02_layers.qmd#sec-pr-depths)                                                                                                 |
|                                    | -   [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) per horizon                                                                              |
|                                    | -   Secondary features: [Pans](hr_04_secondary_features.qmd#sec-pan)                                                                                      |
|                                    | -   Consistence: [Unconfined strength](hr_05_physical_properties.qmd#sec-cn-stru) under field conditions                                                  |
|                                    | -   Substrate: [Paralithic or lithic material](pr_02_layers.qmd#sec-pr-wdeg)                                                                              |
+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Topsoil stoniness                  | [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) as percentage volume within the top 20cm of the profile                                     |
+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Texture class                      | [Texture class](hr_03_texture.qmd#sec-hr-eatxt) of all horizons to 100cm from the soil surface or to the limit of soil material, if shallower            |
+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Drainage                           | [Profile drainage](in_02_interpreted_properties.qmd#sec-in-pdrng) class                                                                                   |
+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Rooting barriers                   | Presence of any [rooting depth restrictions](in_02_interpreted_properties.qmd#sec-in-rdpth) within 100cm of the soil surface, type and depth encountered |
+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+

: Parameters required to identify the NZSC Sibling {#tbl-nzsc-sibid .striped .hover tbl-colwidths="\[40, 60\]"}

### Functional horizon requirements {#sec-in-nzscfh}

+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Parameter         | Requirements                                                                                                                                                 |
+:==================+:=============================================================================================================================================================+
| Horizon notation  | Presence of any [A, O, or L horizons](in_01_horizon_names.qmd#sec-hzn-convp) (for identification of topsoil)                                                 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Texture           | -   [Texture group](hr_03_texture.qmd#sec-hr-eatxt)                                                                                                          |
|                   | -   [Pan](hr_04_secondary_features.qmd#sec-pan) types, if present                                                                                            |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Firmness          | [Unconfined strength](hr_05_physical_properties.qmd#sec-cn-stru) under field conditions                                                                      |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tephric materials | -   [Parent material origin](pr_02_layers.qmd#sec-pr-orig) (specifically Tephra)                                                                             |
|                   | -   Originating [lithology](ss_04_parent_material.qmd#sec-pm-lith) of soil materials \<2 mm                                                                  |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Stone content     | [Rock fragment content](hr_01_architecture.qmd#sec-rockfrag) (either from texture code or percentage estimate)                                               |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Structure         | -   Structure [degree of development](hr_01_architecture.qmd#sec-hr-stru-pedality) (where units are of pedogenic origin)                                     |
|                   | -   If horizon is pedal, ped [shape](hr_01_architecture.qmd#sec-hr-stru-shp) and [size](hr_01_architecture.qmd#sec-hr-stru-size)                             |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Consistence       | -   For [cohesive](hr_05_physical_properties.qmd#sec-dn-prep) soils, [unconfined strength](hr_05_physical_properties.qmd#sec-cn-stru) under field conditions |
|                   | -   For [non-cohesive](hr_05_physical_properties.qmd#sec-dn-prep) soils, [particle packing](hr_05_physical_properties.qmd#sec-sn-pack)                       |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Permeability      | [Horizon permeability](in_02_interpreted_properties.qmd#sec-in-hperm) class                                                                                  |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Parameters required to identify NZSC Functional Horizons {#tbl-nzsc-fhid .striped .hover tbl-colwidths="\[40, 60\]"}
