# The New Zealand Soil Classification {#sec-nzsc123}

Classifying a profile according to the first three levels of the NZSC [@hewitt2024] requires the following steps:

1.  Identify diagnostic features
2.  Follow the Key to Soil Orders
3.  Follow the Keys to Group and Subgroup

## Identifying Diagnostic features

The descriptive parameters that help define the NZSC Diagnostic features are outlined in @tbl-nzsc-diags; see [-@hewitt2024] for the full definitions. Any or all of the listed parameters may be required for a confident diagnosis.

+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Diagnostic feature              | Identification requirements                                                                                                                                                                                                                                                                                                     |
+:================================+:================================================================================================================================================================================================================================================================================================================================+
| **Horizons, pans and layers**   |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Argillic horizon                | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist)                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec) (relative to overlying horizon)                                                                                                                                                                                                                                                   |
|                                 | -   [Coatings](hr_04_secondary_features.html#sec-hr-coat) *or* lamellae                                                                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Brittle-B horizon               | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Roots](hr_01_architecture.html#sec-root)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail)                                                                                                                                                                                                                                                  |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Calcareous horizon              | -   Calcium carbonate [concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                  |
|                                 | -   Field test: [Calcium carbonate](hr_06_chemical_properties.html#sec-ft-ca)                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cutanic horizon                 | -   [Coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                                                                                                       |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cutanoxidic horizon             | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail), [stickiness](hr_05_physical_properties.html#sec-cn-sti), [plasticity](hr_05_physical_properties.html#sec-cn-pla)                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Densipan                        | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                                                                                             |
|                                 | -   Field test: [Slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Distinct topsoil                | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix) (relative to deeper horizon)                                                                                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Duripan                         | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Field test: [Reaction to HCl](hr_06_chemical_properties.html#sec-ft-ca), [slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Eluvial horizon                 | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fragipan                        | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Roots](hr_01_architecture.html#sec-root)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail), [unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                              |
|                                 | -   Field test: [Slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Humus-pan                       | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail), [unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ironstone-pan                   | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist) (upper)                                                                                                                                                                                                                                                    |
|                                 | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Consistence: [Induration](hr_05_physical_properties.html#sec-cn-ind)                                                                                                                                                                                                                                                        |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Nodular horizon                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc)                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ortstein-pan                    | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist) (upper)                                                                                                                                                                                                                                                    |
|                                 | -   [Pans](hr_04_secondary_features.html#sec-pan)                                                                                                                                                                                                                                                                               |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                                                                                             |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Oxidic Horizon                  | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [ped strength](hr_05_physical_properties.html#sec-cn-stra), [mode of failure](hr_05_physical_properties.html#sec-cn-fail), [stickiness](hr_05_physical_properties.html#sec-cn-sti), [plasticity](hr_05_physical_properties.html#sec-cn-pla) |
|                                 | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf), [slaking](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Peaty topsoil                   | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Placic horizon                  | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist) (upper and lower)                                                                                                                                                                                                                                          |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   Consistence: [Induration](hr_05_physical_properties.html#sec-cn-ind)                                                                                                                                                                                                                                                        |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Podzolic-B horizon              | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Coatings](hr_04_secondary_features.html#sec-hr-coat) and [concentrations](hr_04_secondary_features.html#sec-hr-conc)                                                                                                                                                                                                       |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru)                                                                                                                                                                                                                                              |
|                                 | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf)                                                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Redox-mottled horizon           | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reductimorphic horizon          | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slowly permeable layer          | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Penetration resistance](hr_05_physical_properties.html#penetration-resistance)                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Weathered-B horizon             | -   [Matrix colour](hr_02_colour.html#sec-col-matrix) (relative to deeper layers)                                                                                                                                                                                                                                               |
|                                 | -   [Structure](hr_01_architecture.html#sec-hr-stru) (relative to deeper layers)                                                                                                                                                                                                                                                |
|                                 | -   Evidence of carbonate loss (relative to deeper layers)                                                                                                                                                                                                                                                                      |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Soil materials and contacts** |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allophanic soil material        | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf)                                                                                                                                                                                                                                                                |
|                                 | -   Consistence: [Unconfined strength](hr_05_physical_properties.html#sec-cn-stru), [sensitivity](hr_05_physical_properties.html#sec-cn-sens), [stickiness](hr_05_physical_properties.html#sec-cn-sti)                                                                                                                          |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Anthropic soil material         | -   [Artefacts](hr_01_architecture.html#sec-hr-artef) and/or [plastics](hr_01_architecture.html#sec-hr-plas)                                                                                                                                                                                                                    |
|                                 | -   [Recent site disturbances](pr_00_intro.html#sec-pr-dist)                                                                                                                                                                                                                                                                    |
|                                 | -   [Landform](ss_03_landscape.html#sec-gmph-lfm) (Human-induced)                                                                                                                                                                                                                                                               |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lithic contact                  | -   Substrate rock presence                                                                                                                                                                                                                                                                                                     |
|                                 | -   Horizon degree of weathering                                                                                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Organic soil material           | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Mode of failure](hr_05_physical_properties.html#sec-cn-fail)                                                                                                                                                                                                                                                  |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Paralithic contact              | -   Substrate rock presence                                                                                                                                                                                                                                                                                                     |
|                                 | -   Horizon degree of weathering                                                                                                                                                                                                                                                                                                |
|                                 | -   [Roots](hr_01_architecture.html#sec-root)                                                                                                                                                                                                                                                                                   |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Saline soil material            | -   Field test: [Electrical conductivity](hr_06_chemical_properties.html#sec-ft-ec)                                                                                                                                                                                                                                             |
|                                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                                    |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sulfidic soil material          | -   Field test: [pH in water](hr_06_chemical_properties.qmd#sec-ft-phfw) and [pH in hydrogen peroxide](hr_06_chemical_properties.qmd#sec-ft-phfox)                                                                                                                                                                              |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sulfuric soil material          | -   Field test: [pH in water](hr_06_chemical_properties.qmd#sec-ft-phfw)                                                                                                                                                                                                                                                        |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat) (especially jarosite)                                                                                                                                                                              |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tephric soil material           | -   [Lithology](ss_04_parent_material.html#sec-pm-lith)                                                                                                                                                                                                                                                                         |
|                                 | -   [Mineralogy](ss_04_parent_material.html#mineralogy)                                                                                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Vitric soil material            | -   [Rock fragments](hr_01_architecture.html#sec-rockfrag)                                                                                                                                                                                                                                                                      |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   [Lithology](ss_04_parent_material.html#sec-pm-lith)                                                                                                                                                                                                                                                                         |
|                                 | -   [Parent material origin](hr_00_intro.html#parent-material-origin)                                                                                                                                                                                                                                                           |
|                                 | -   [Mineralogy](ss_04_parent_material.html#mineralogy)                                                                                                                                                                                                                                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Profile forms**               |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gley profile form               | -   [Horizon depths](pr_02_layers.html#sec-pr-depths)                                                                                                                                                                                                                                                                           |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   Field test: [Reducing conditions](hr_06_chemical_properties.qmd#sec-ft-rdx)                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mottled profile form            | -   [Horizon depths](pr_02_layers.html#sec-pr-depths)                                                                                                                                                                                                                                                                           |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Features**                    |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fluvial features                | -   [Horizon thickness](pr_02_layers.qmd#sec-pr-depths)                                                                                                                                                                                                                                                                         |
|                                 | -   [Horizon boundary distinctness](pr_02_layers.qmd#sec-pr-bdydist)                                                                                                                                                                                                                                                            |
|                                 | -   [Rock fragments](hr_01_architecture.html#sec-rockfrag)                                                                                                                                                                                                                                                                      |
|                                 | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                                                                                                                                                                                                                   |
|                                 | -   Consistence: [Fluidity](hr_05_physical_properties.html#sec-cn-flu)                                                                                                                                                                                                                                                          |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Perch-gley features             | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
|                                 | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc) and/or [coatings](hr_04_secondary_features.html#sec-hr-coat)                                                                                                                                                                                                    |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sodic features                  | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                                                                                                                                                                                                                            |
|                                 | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   Field test: [Dispersion](hr_06_chemical_properties.html#sec-ft-slak)                                                                                                                                                                                                                                                        |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Other differentiae**          |                                                                                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Childs' Test                    | -   Field test: [Reducing conditions](hr_06_chemical_properties.qmd#sec-ft-rdx)                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Low-chroma colours              | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                                                                                                                                                                                                                           |
|                                 | -   [Colour patterns](hr_02_colour.html#sec-col-patt)                                                                                                                                                                                                                                                                           |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reactive-aluminium test         | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf)                                                                                                                                                                                                                                                                |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Redox segregations              | -   [Concentrations](hr_04_secondary_features.html#sec-hr-conc)                                                                                                                                                                                                                                                                 |
+---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Description requirements for NZSC Diagnostic Features [@hewitt2024] {#tbl-nzsc-diags .striped .hover tbl-colwidths="\[40, 60\]"}

## Following the Key to Orders

In addition to the diagnostics above, successful navigation of the Key may require documentation of the following:

+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Order            | Requirement                                                                                                                    |
+:=================+:===============================================================================================================================+
| Anthropic Soils  | Evidence of profile truncation or filling (compare site with surrounding landform(s))                                          |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Organic Soils    |                                                                                                                                |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Gley Soils       | -   [Buried horizons](in_01_horizon_names.html#sec-hzn-bur)                                                                    |
|                  | -   Consistence: [Fluidity](hr_05_physical_properties.html#sec-cn-flu)                                                         |
|                  | -   Field test: [Reducing conditions](hr_06_chemical_properties.html#sec-ft-rdx)                                               |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Ultic Soils      | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                           |
|                  | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                          |
|                  | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                  |
|                  | -   [Clay content](https://manaakiwhenua.github.io/NZ_soildesc_2024/hr_03_texture.html#sec-tex-pse) (relative to silt)         |
|                  | -   Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Podzols          | Field test: [pH](hr_06_chemical_properties.html#sec-ft-phf)                                                                    |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Allophanic Soils |                                                                                                                                |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Pumice Soils     |                                                                                                                                |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Melanic Soils    | -   [Lithology](ss_04_parent_material.html#sec-pm-lith)                                                                        |
|                  | -   [Surface cracking](pr_01_surface.html#sec-pr-crack)                                                                        |
|                  | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                           |
|                  | -   [Rock fragments](hr_01_architecture.html#sec-rockfrag)                                                                     |
|                  | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                          |
|                  | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                  |
|                  | -   Degree of weathering                                                                                                       |
|                  | -   Consistence: [Stickiness](hr_05_physical_properties.html#sec-cn-sti)                                                       |
|                  | -   Field test: [Calcium carbonate](hr_06_chemical_properties.html#sec-ft-ca), [pH](hr_06_chemical_properties.html#sec-ft-phf) |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Semiarid Soils   | Field test: [Calcium carbonate](hr_06_chemical_properties.html#sec-ft-ca), [pH](hr_06_chemical_properties.html#sec-ft-phf)     |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Oxidic Soils     |                                                                                                                                |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Granular Soils   | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                           |
|                  | -   [Rock fragments](hr_01_architecture.html#sec-rockfrag)                                                                     |
|                  | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                  |
|                  | -   Degree of weathering                                                                                                       |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Pallic Soils     | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                          |
|                  | -   Field test: [Dispersion](hr_06_chemical_properties.html#sec-ft-slak)                                                       |
|                  | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf) (negative)                                                    |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Brown Soils      | -   [Matrix colour](hr_02_colour.html#sec-col-matrix)                                                                          |
|                  | -   [Texture](hr_03_texture.html#sec-tex-rec)                                                                                  |
|                  | -   Field test: [NaF](hr_06_chemical_properties.html#sec-ft-naf) (no more than moderate)                                       |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Recent Soils     | -   [Structure](hr_01_architecture.html#sec-hr-stru)                                                                           |
|                  | -   Consistence: [Fluidity](hr_05_physical_properties.html#sec-cn-flu)                                                         |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Raw Soils        |                                                                                                                                |
+------------------+--------------------------------------------------------------------------------------------------------------------------------+

: Additional description requirements for NZSC Key to Orders [@hewitt2024] {#tbl-nzsc-key .striped .hover tbl-colwidths="\[40, 60\]"}
