# Soil Description Handbook - New Zealand {.unnumbered}

**v 2.0**

This edition supersedes Milne 1995

*publishing info goes here eventually*

# Foreword to the third edition

The revised edition of the Soil Description Handbook @milne1995 has been a steady companion to the New Zealand pedologist for nearly thirty years. This should tell us something very complimentary about the quality of the original publication! Nonetheless, as time marches on, elements of the standard have become out of date and require a refresh - notably, a response to the ever-advancing use of technology in the field. Additionally, the structure and layout of the book make it somewhat challenging to develop it into a structured database capable of storing, analysing and publishing high quality soils data.

This update has been in the works for over five years, but has unfortunately struggled to compete with the pressing demands of our soil mapping and research workload. The past year involved a major push to get the new draft into a stable enough state that external review is now possible. A summary of the changes proposed can be seen in [Appendix F](changelog.qmd). We expect the draft to continue to evolve over the next year or so into a final document that suits not only Manaaki Whenua's expert pedologists, but soils workers throughout New Zealand. 

This new draft edition of the Handbook was compiled by Lauren O'Brien, in consultation with Andre Eger, Balin Robertson, Kirstin Deuss, Thomas Caspari, Veronica Penny, Lena Reifschneider, Scott Fraser, Emily Mackay, Anthony Ward, Malcolm McLeod, Trevor Webb, and Ian Lynn. The project would not have been possible without the support of Sam Carrick, Linda Lilburne and Andrew Manderson.

Lauren O'Brien
Manaaki Whenua - Landcare Research
2024-11-17