# Introduction {.unnumbered}

The aim of updating the *Soil Description Handbook for New Zealand* is to produce a document that can enable a soils professional to describe a soil profile and its landscape context in a way that effectively informs agronomic, ecological, and research applications. These applications include:

- soil mapping at regional and farm scales
- land use evaluations (e.g. crop suitability assessments)
- on-farm decision-making (e.g. determining fertiliser application rates)
- land restoration activities (e.g. native ecosystem rehabilitation, tree establishment).

Engineering applications are considered out of scope, but links can and should be made between this standard and international and New Zealand geotechnical standards.

The handbook aims to support the requirements of the fourth edition of the *New Zealand Soil Classification* [@hewitt2025], and, wherever possible, to be compatible with international soil description and classification standards.

The handbook is organised into four sections:

- **Soil setting**: focuses on the main soil forming factors operating in the New Zealand landscape, and how to contextualise a soil profile description using relevant data sources. This includes accurate location within the landscape, as well as description of geomorphology, parent materials, climate, biota, land cover, land use and land management. The section also includes information about other soil knowledge resources in New Zealand.
- **Soil surface and profile**: focuses on recording appropriate metadata for a soil profile description, describing the immediate area around the profile, and describing the down-profile sequence of horizons and substrate layers.
- **Soil horizons**: focuses on describing the pedological character of each horizon or layer in the soil profile, including physical architecture (structure, type and arrangement of solids and voids), colour, texture and weathering features. Instructions for assessing soil physical consistence and some field-assessable chemical parameters follow.
- **Soil interpretations**: describes a notation system for soil horizons, methods of assessing overall profile behaviour in terms of local hydrology, and a guide showing which descriptive parameters are relevant to each part of the *New Zealand Soil Classification*.

Several appendices follow, which contain information on appropriate field equipment and recording standards, methods of profile exposure, description and sampling procedures, instructions for classifying numeric field parameters, and information on compatibility with related soil and landscape description systems.

Further supporting documents are available on the New Zealand Soils Portal, including field recording sheets and an example data model.

## Major changes in the fourth edition

This handbook is a substantial rewrite of @milne1995 and was undertaken at the same time as revision of the *New Zealand Soil Classification* (NZSC). As well as the structural changes described above, both reviews focused on improving cross-compatibility and consistency. This has led to some updates to terminology in both books. New parameters were also added, largely to enable the user to more clearly describe soil features that are diagnostic in the NZSC.

New content in the 'soil setting' section includes updated discussion of modern means of determining spatial location, as well as an updated system to describe the geomorphology around a soil profile description at multiple scales. A new lithology term list is also available. Where description standards exist already, the user is referred to those rather than reinventing the wheel – this includes standards for vegetation, climate, land cover, land use, and land management. A short chapter highlighting other sources of soils knowledge and information relevant to New Zealand has been added at the end of the section.

The 'soil surface and profile' section contains some new reference data parameters, as well as new parameters for describing various aspects of the land surface and the soil profile. Some additional ability to describe the 'subsolum' below the soil profile is also now available. The instructions for defining horizons are otherwise consistent with previous standards.

Overall, the 'soil horizons' section will be most familiar to users familiar with the previous standard. Descriptions of structure, texture, colour, weathering features and other soil materials remain consistent, but some new details can be recorded. For example, soil texture class definitions have not changed, but they can now be appended with information about rock fragment and organic matter content, where needed. Consistence tests and in-field chemical tests now have clearer instructions and appropriate safety warnings.

Finally, the 'soil interpretations' section contains a slightly updated horizon notation system, as well as instructions for assessing profile behaviour in terms of drainage, permeability, and barriers to root growth. A series of tables clearly relating different parts of the recording standard to elements of the NZSC rounds out the section.

Horizon notation remains largely identical to previous publications, although the layout of the chapter has been rearranged to better distinguish between primary, secondary, and supplementary notation and to reduce redundancy. Minor clarifications to the definitions of some symbols have been made to better align the system with the NZSC, and clear definitions of the redox suffixes have been added. Changes to the system are otherwise as follows.

- the 'L' primary horizon has been repurposed, from previously describing fresh leaf litter to now describing organic horizons developing under largely unsaturated conditions (this replaces both F and H horizons). This allows a parallel set of horizons to those used for peats (Lf, Lh, Lm vs Of, Oh, Om) and aligns more closely with the texture code system. The former F horizon would now be recorded as 'Lm' and H as 'Lh'. 'Lf' is effectively a new option for organic material that is no longer fresh but still little-decomposed, most likely due to having a high fibre and/or lignin content (e.g. palm fronds). Fresh litter presence at a site is now recorded when describing land surface cover.
- the 'u' subscript has been re-purposed to describe fluid horizons (which were previously denoted using 'e'), and can be used with A, E, B or C horizons.
- the 'l' suffix has been re-purposed from denoting gibbsite accumulation to describing accumulation of groundwater-sourced iron-rich precipitates (e.g. soft masses, nodules and iron-pans). This is because gibbsite occurrence is not diagnostic in the NZSC, but iron precipitation is. The usage is now also consistent with the *World Reference Base*. Gibbsite nodule occurrence can still be described directly as a weathering feature.
- the 'e' prefix has been added for the purpose of highlighting anthropogenic horizons.

Throughout the book, options are presented for recording data at multiple levels of detail, and whether a parameter is always required is made clear.

Finally, the way in which some parameters are recorded has changed. Inherently numeric properties are now preferentially recorded as numbers; either single measurements, median-plus-range, or low-high range as appropriate. Options for classifying these numeric parameters for ease of communication are presented in the Soil Interpretations section. Numeric data classified in the field has limited re-use potential (in that it cannot be combined with the same data recorded against other classification systems), and the ranges have limited resolution. Many numeric soil parameters have no inherent natural breaks, but patterns in their distribution can emerge in specific landscapes or over certain scales of examination. Recording such data to classes in the field reduces the likelihood of ever revealing those patterns clearly.
