# Land surface

-   scale is landform - immediate surrounds

## Surface cover

-   record components as percent composition of the following categories:
    -   bare ground (sediment or soil, \<2mm)
    -   bare rock fragments, shells, or bones
    -   bare rock outcrop
    -   open water/ice/snow
    -   peat
    -   dry leaf litter (includes seed pods)
    -   grass/moss/herbs/annual crops
    -   stems/trunks/roots/perennial crops
    -   sealed (building, concrete, asphalt etc.)
    
[Turn the above into a 3x3 grid with labels underneath conceptual diagrams]{style="background-color:lightgreen"}

-   record only to nearest 5-10%, no need to get carried away. It will be unusual to encounter more than three components at any one site.
-   this should be able to be connected back to landform characteristics - don't repeat yourself here by e.g. recording lithology again

[unresolved: assess to what height? I'm thinking like, 20cm tops]{style="background-color:lightgreen"}

```{r}

# draw donut chart with 10% breaks next to a couple of pictures for examples



```

## Surface condition

-   aus list should be ok - but that requires dry conditions, something of an issue in NZ
-   include crusts here

## Surface cracking

-   modal width
-   modal distance
-   spatial arrangement (note connection to freeze-thaw, slip)
-   note: WRB includes crack persistence but this might be a problem - speculative
-   note: requires season and recent weather data for context

## Surface water

-   (where known)
-   flood frequency basically (use wrb list)

## Microrelief

-   get something a bit simpler out of the aus and wrb systems
-   nz - creep and slump features, terracettes, etc

## Anthropogenic alterations

-   start with WRB list but needs some development/local tuning
