# Landscape

-   setup - going big to small
-   purpose - interpretive context
- note: discuss when a DEM/terrain derivatives can and can't be used post-field

## Regional landscape

-   scale: 100s-1000s of meters (ref Ontario guide for this idea)
-   don't have a nationally accepted ecozone system yet
-   do have LUC (brief discussion)
-   do have SMap landform trees (brief discussion)

### Relief

### Modal slope

### RMS

-   adapt from aus

### Mesoscale topographic index

- ref to RECCE, connect to Geomorphons concept

### Landscape description

-   shortcut terms, noting that they don't form a conceptual tesselation
-   longform descriptions

------------------------------------------------------------------------

## Local landform

-   scale: 1-10s of meters around site
-   starting with simple measurements and moving to more interpretive ones

### Slope

-   gradient - range, units, precision

### Aspect

-   direction - range, units, precision, *direction*

### Slope morphology

-   pick up aus system and tweak

### Slope length

-   mention RUSLE connection

### Active geomorphic agents

-   eroded vs aggraded then types

### Landform description

-   shortcut terms, noting that they don't form a conceptual tesselation
-   longform descriptions

