# Biota {#sec-biota}

```{r}
library(dplyr)
library(tibble)
library(gt)
```

Soil biota both affects and is affected by soil type. For example, Kauri trees create acidic conditions around their root zone, leading to the development of podzolic features.

## Vegetation {#sec-veg}

Recording vegetation during soil survey can reveal relationships between soil and vegetation community composition and structure.

Three options are available in New Zealand for recording vegetation data in a soils context.

-   A detailed assessment of vegetation at a soil site can be made using the RECCE standard [@hurst2022]. This is the method used by the [NZ National Vegetation Survey](https://nvs.landcareresearch.co.nz/), and it allows creation of a complete record of vegetation structure and species assemblage. Some elements of the RECCE standard have been adopted elsewhere in this manual, where relevant to describing the landscape and land surface (@sec-gmph-other, @sec-pr-surfcov). Note that considerable botanical experience is needed to apply the full RECCE standard correctly.
-   If the soil description is being completed in the context of a Land Use Capability (LUC) assessment, use the NZLRI Vegetation Descriptions available in Appendix 3 of the LUC Handbook [@lynn2009]. This system describes a set of 49 vegetation communities commonly found in New Zealand, grouped into five broad structural categories (grasses, crops, scrub, forest, and herbaceous). Ability to identify key local species will be required to apply the system correctly. The system can also be used for routine vegetation assessment during other soil mapping activities.
-   For very rapid assessment, recording landform-scale LCDB land cover (@sec-lcov) will convey both land cover and basic vegetation information.

Simpler systems that attempt to break vegetation communities into key structural classes are available, including the 'Atkinson system' recommended in the previous version of this manual. These are easy to apply but may not adequately discriminate between vegetation communities in a way that is soils-relevant.

Note that vegetation condition assessment is beyond the scope of this document.

## Soil Fauna {#sec-fauna}

### Megafauna {#sec-fauna-mega}

Soil megafauna are large species that may not be directly dependant on the soil for any part of their life cycle, but still significantly and directly affect the soil, usually by mechanical disturbance or organic material addition. In New Zealand this role was largely filled by native earthworms, birds and reptiles before the arrival of humans. Since then, the niche has been dominated by domesticated sheep, goats and cows, as well as feral goats, pigs and rabbits. Significant increases in the volume of animal wastes added to many soils have also occurred, most intensely on land converted to pastoral agriculture. Introduction of exotic earthworms and dung beetle species has followed.

The influence of these animals is generally captured elsewhere in a soil description (e.g. @sec-pr-dist) and so no further morphology recording requirements are defined in this handbook.

Direct assessment of earthworm presence in the topsoil is sometimes desired [@shepherd2000; @shepherd2000a]. Optionally, record the number of earthworms observed in a 20 x 20 cm block of A horizon. Calculate the volume of the sample examined and convert the count to a rate per cubic metre.

### Macrofauna {#sec-fauna-midi}

Macrofauna are those soil-dwelling animals with a body width of \~2 - 20 mm. The influence of these animals is generally captured in a soil description as infill features (@sec-pr-inf) or voids (@sec-void). In New Zealand, soil bioturbation by macrofauna has been relatively minimal, excepting some native dung beetles.

### Meso- and Microfauna {#sec-fauna-mini}

The soil Meso- and Microfauna are much smaller, with body widths of 0.1 - 2.0 mm and \< 0.1 mm respectively. They live mostly within soil pores and have little direct impact on structure. Their presence, however, is a sign that soil porosity is well enough developed to provide them with a habitat. No observational requirements are defined for Meso- or Microfauna at this time.
