# Background {#sec-bg}

The soil profiles that pedologists describe are components of a larger landscape, and both influence and are influenced by their surrounds. To bring structure to the information we gather about the profile surrounds, the available inputs can be grouped into a suite of 'soil forming factors'. These are commonly conceptualised in soils literature using the 'clorpt' model, whereby soils are considered to be a product of interactions of:

- **cl**imate
- **o**rganisms
- **r**elief
- **p**arent Material
- **t**ime

(see [@jenny1941; @schaetzl2015; @brevik2016]). The first section of this handbook is loosely organised around these factors and describes where information on them can be found (specific to the New Zealand context), along with certain parameters that may (or must) be measured directly in the field.

Throughout this handbook, recording options are presented for rapid, routine, and detailed logging of soil profile description data. It is up to the surveyor to decide the level of detail needed for each description, but in general the detailed options are most appropriate for reference descriptions and research tasks, the routine options for the exploration phase of mapping, and the rapid options for map validation or checking the degree of soil variability in the vicinity of a more detailed description. Even the rapid logging requirements will support classification according to the *New Zealand Soil Classification* [@hewitt2025] to at least the subgroup level. A summary of the three detail levels is available in @sec-mds.
