# Soils {#sec-soil}

Most parts of New Zealand have at least some existing soils knowledge documented in various forms. These resources can be a valuable starting point when conducting new research or survey work.

## Māori soil knowledge {#sec-soil-m}

The traditional Māori understanding of soils and its development into modern systems can be explored in @harmsworth2014, @harmsworth2014a, and @harmsworth2022.

## Legacy soil mapping {#sec-soil-leg}

Post-settlement soil mapping in New Zealand started as early as the 1910s. Many of these records have been digitised and can be explored on the Manaaki Whenua [Legacy Map Viewer](https://soils.landcareresearch.co.nz/tools/legacy-map-viewer). Accompanying reports are available from the Manaaki Whenua [Digital Library](https://soils.landcareresearch.co.nz/resources/soil-publications/soil-publications-dl). Pātaka Oneone, the [Manaaki Whenua Soils Portal](https://soils.landcareresearch.co.nz/), offers many more resources for accessing knowledge about New Zealand's soils.

As well as mapping in New Zealand itself, New Zealand pedologists have worked extensively in the Pacific. Reports and maps for many islands are available from the [Digital Library](https://soils.landcareresearch.co.nz/resources/soil-publications/soil-publications-dl), and the data from that work have been compiled in a modern format for the [Pacific Soils Portal](https://psp.landcareresearch.co.nz/).

## Modern soil mapping {#sec-soil-mod}

The flagship regional-scale soil mapping product for New Zealand is S-map. Information about S-map, including a web-based interactive map, is available at [S-map online](https://smap.landcareresearch.co.nz/).

## Books about New Zealand soils {#sec-soil-books}

Key companion standards to this handbook are the *New Zealand Soil Classification* and *Criteria for Defining the Soil Family and Soil Sibling* [@webb2011]. Together these documents allow New Zealand soil information to be efficiently recognised and communicated. Further information about how the classification was formulated can be found in the *Methods and Rationale of the New Zealand Soil Classification* [@hewitt1993].

The reader is encouraged to explore the reference list in this handbook ([References](references.qmd#sec-refs)). General references of particular value are *Soils in the New Zealand Landscape: The Living Mantle* [@molloy1998], which is [available for download](https://www.soilscience.org.nz/books/soils-in-the-new-zealand-landscape-the-living-mantle) from the New Zealand Soil Science Society, and *The Soils of Aotearoa New Zealand* [@hewitt2021].
