# Background

The soil profiles that pedologists describe are components of a larger landscape, and both influence and are influenced by their surrounds. To bring structure to the information we gather about the profile surrounds, the available inputs can be grouped into 'soil forming factors'. These are commonly conceptualised in soils literature using the 'clorpt' model, whereby soils are considered to be a product of interactions of **Cl**imate, **O**rganisms, **R**elief, **P**arent Material and **T**ime [@jenny1941]. This section is loosely organised around these factors and describes where information on them can be found (specific to the New Zealand context) and certain parameters that may (or must) be measured directly in the field.

The reference data section is additional to these factors and describes essential metadata that must be appended to soil profile description in order for it to be useful. Following that are chapters on Location, Relief (or more correctly, Geomorphology), Parent Material (including geology), Climate and Weather, and Biota. Land cover, land use and management are discussed in their own chapter, but in many ways the parameters contained within describe the specific influence of one element of the biota - humans. Lastly, since available soils information can help extend understanding of soil distribution, a short summary of existing soil knowledge resources in New Zealand finishes out the section. Time is discussed where relevant within these chapters.
