# Location

## Absolute location

-   appropriate coordinate systems - horizontal plus vertical

-   vertical - absolute elevation, elevation above local low point/drainage

-   measuring equipment

-   required precision for various applications

-   storing spatial data (i.e. use points) (too in the weeds???)

-   NZ-specific concerns e.g. earthquake shifts, uplift (feed in epoch concept too)

-   temporal - YYYY-MM-DD

-   notes

    -   use of alternative coord systems e.g. w3w (i.e. don't)
    -   use of DGGS (stick to post-processing for now)

## Relative location

### triangulating off local features

-   what counts as sufficiently permanent
-   when to bother (e.g. poor location signal)

### longform descriptions

-   site approach instructions
-   importance for relocating monitoring points

### region data

-   talk about when to tag sites to human administrative boundaries
-   options: regional, district council; property boundaries
-   code list for RCs?

### temporal

-   season
-   time since significant weather events (see FAO)

## Explaining location

-   i.e. why and how the spot was singled out; when this matters
-   codes for why
-   codes for how

------------------------------------------------------------------------
